### ISSUE TITLE
Support xla_hlo.convert operation on Structured Ops Path to SPIR-V

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#1687]
Lowering `xla_hlo.convert` operations to SPIR-V on Structured Ops path requires use of std.trunci, std.sitofp, std.truncf, etc. The lowering from XLA-HLO to Linalg is fairly easy to add (the existing XLA-LHLO to Linalg lowering can be reused), but legalizing the std instructions to SPIR-V requires effective handling of integer widths.

**Comment by hanhanW** [comment]
I studied a bit on this issue since I'm working on integer width adjustment. I have a CL chain to pass the test except the last test case -- float_to_int. I haven't figured out the reason, will take a look later.

**Comment by hanhanW** [comment]
Just found that the reason is quite simple.

We don't have a pattern to convert floating point to integer in map_xla_to_scalar_op.h
I don't know why, it seems that there is only SIToFPOp in Standard Dialect, but no FPToSIOp. It would be super easy to support once there is something like FPToSIOp in Standard Dialect.
