### ISSUE TITLE
Building IREE components with CMake requiring TensorFlow

### ISSUE THREAD

**Issue by marbre** [google/iree#179]
Several components within IREE require some TF libs and thus cannot be build with CMake at the moment. For example `iree::python::tensorflow_impl` pulls in

-  `@org_tensorflow//tensorflow/cc/saved_model:loader_lite` and
-  `@org_tensorflow//tensorflow/compiler/mlir/tensorflow`,

whereas the latter is also pulled in by `iree::integrations::tensorflow::compiler::tensorflow`. How should we handle this? For `tensorflow::mlir_xla` an _ovleray_ `CMakeLists.txt` is already provided (build_tools/third_party/tensorflow/tensorflow/compiler/mlir/xla/CMakeLists.txt).

Prior to start working on CMake files, I would like to ask if there are already plans or expectations for all the required but still missing TF deps?

**Comment by ScottTodd** [comment]
@stellaraccident has the most complete view of how the Python and TensorFlow dependencies are set up. I can give a bit of background first:

Some of our [original thoughts](https://github.com/google/iree/blob/e3615bfe78014e7f174b034e1d2786ba35b6bed3/README.md#build-system-and-ci) were to support Bazel for the entire project and CMake for the parts that we expect most developers using IREE in other systems to need. The TensorFlow dependency in particular has, at least historically, been difficult to prune to a reasonable enough subset to support building with other build systems. If the required pieces of TensorFlow have been trimmed enough, then supporting a CMake build on our end may be possible (though having that be upstreamed into TensorFlow itself would also be nice).

TensorFlow is mainly used for model authoring and experimentation, then lowering to MLIR/XLA. Once models are in MLIR/XLA, IREE's compiler can handle them without a TensorFlow dependency. We may also (see issue #15) publish a Docker image for use with Colab that will let developers skip that setup.

**Comment by stellaraccident** [comment]
This is moving around a bit at present, so take the following as the current snapshot.

I eventually want to relocate all of the non-XLA TensorFlow deps to integrations/tensorflow and pull them in with some kind of a plugin interface that won't pollute the overall build. The TensorFlow team iteself removed their own CMake files some time ago, which is a decision that I have opinions about but no influence to change at this point.

The exception, as you note is the tensorflow/compiler/xla directory (the subset that we use at least). I believe it is tenable to maintain an overlay CMake build for this and the core compiler does need to have this dep.

I am holding off on more surgery on this until MLIR lands in LLVM, as currently the way we maintain the shared commit hashes and upstream/downstream links between those projects is challenging, and fixing it becomes easier once the integration is done (and I'd rather do the work once). That should be happening soon (Mehdi has a draft of the proposal), but if not, we'll just untangle it as-is. I know that this may not seem related for build support, but suffice to say there are some tricky things under the surface that are maintaining the single-version constraints.

So, if working on CMake build files now, you should be able to cordone off anything in integrations/tensorflow and bindings/python/pyiree/tf_interop (with the latter eventually collapsing into the former). There should already be header/ifdef trampolines in place on these, but if insufficient, we can further isolate them however is helpful.

Because we use Bazel for all of our internal integrations of IREE, we've got to support it no matter what, but if we can get the CMake setup up to par, I'm willing to make that the primary thing we point the community at (at least for the non-TensorFlow parts).

**Comment by marbre** [comment]
Thanks for the detailed responses. Will get back to this asap.

**Comment by marbre** [comment]
I think with splitting the python bindings into `bindings/python/pyiree` and `integrations/tensorflow/bindings/python/pyiree/` this is solved as far as it can be solved at this moment. The follow up discussion was https://groups.google.com/forum/#!topic/iree-discuss/V1IJD9IZs-M.

Can be closed from my point of view.
