### ISSUE TITLE
PrepareForLLVMLoweringPass failing on resnet50

### ISSUE THREAD

**Issue by asaadaldien** [google/iree#1838]
"Somehow" PrepareForLLVMLoweringPass crashes applying the pattern wih the following resnet50 IR:
 
IR:(resnet_bug.mlir)
https://gist.github.com/asaadaldien/142a05eadc6e8ef1c2c830915c30ca78

Repro:
```
iree-run-mlir -iree-hal-target-backends=llvm-ir resnet50_bug.mlir --input-value=1x32x32x3xf32  --mlir-disable-threading
```

Crash:
```
assert.h assertion failed at third_party/llvm/llvm-project/mlir/include/mlir/IR/Value.h:81 in bool mlir::Value::isa() const [U = mlir::BlockArgument]: *this && "isa<> used on a null type."
*** Check failure stack trace: ***
    @     0x5617b8b32630  absl::logging_internal::LogMessage::DieIfFatal()
    @     0x5617b8b31f03  absl::logging_internal::LogMessage::SendToLog()
    @     0x5617b8b311ce  absl::logging_internal::LogMessage::Flush()
    @     0x5617b8b33488  absl::logging_internal::LogMessageFatal::~LogMessageFatal()
    @     0x5617b8b2f130  __assert_fail
    @     0x5617b46dd07d  mlir::Value::isa<>()
    @     0x5617b46d76ec  mlir::Value::dyn_cast<>()
    @     0x5617b5752d3c  mlir::Value::getType()
    @     0x5617b43db6f5  mlir::ValueTypeIterator<>::unwrap()
    @     0x5617b43dc1b5  mlir::ValueTypeIterator<>::operator*()
    @     0x5617b47c9a7d  llvm::interleave<>()
    @     0x5617b47c9a1f  llvm::interleave<>()
    @     0x5617b47c9974  llvm::interleaveComma<>()
    @     0x5617b47c9809  llvm::interleaveComma<>()
    @     0x5617b48bcdca  mlir::OpAsmPrinter::printFunctionalType<>()
    @     0x5617b566fe3a  mlir::OpAsmPrinter::printFunctionalType()
    @     0x5617b56660b9  (anonymous namespace)::OperationPrinter::printGenericOp()
    @     0x5617b56685c9  (anonymous namespace)::OperationPrinter::printOperation()
    @     0x5617b566103c  (anonymous namespace)::OperationPrinter::print()
    @     0x5617b5661709  (anonymous namespace)::OperationPrinter::print()
    @     0x5617b566620c  (anonymous namespace)::OperationPrinter::printRegion()
    @     0x5617b5667cfb  (anonymous namespace)::OperationPrinter::printGenericOp()::$_19::operator()()
    @     0x5617b5667c6c  llvm::interleave<>()
    @     0x5617b5667c1e  llvm::interleave<>()
    @     0x5617b5667bb4  llvm::interleaveComma<>()
    @     0x5617b5667750  (anonymous namespace)::ModulePrinter::interleaveComma<>()
    @     0x5617b5665fe5  (anonymous namespace)::OperationPrinter::printGenericOp()
    @     0x5617b56685c9  (anonymous namespace)::OperationPrinter::printOperation()
    @     0x5617b566103c  (anonymous namespace)::OperationPrinter::print()
    @     0x5617b5660c15  mlir::Operation::print()
    @     0x5617b5660a84  mlir::Operation::print()
    @     0x5617b57225b9  mlir::Operation::emitError()
```

**Comment by antiagainst** [comment]
Interesting. Are you able to isolate the commit that causes this issue? Or is this failing from the very beginning of my change for plumbing dynamic shape through SPIR-V CodeGen?

It seems there is a compounding issue in dialect conversion and the `ProcessFuncInterfacePattern` pattern which causes the dumping of the failed-to-legalize FuncOp to crash. 

But I guess the real issue is that when converting from Linalg on tensors to Linalg on buffers, we create `iree.placeholder` op just *before* the Linalg op using it. The case here we have multiple Linalg ops so it ends up we have `iree.placeholder` ops scattered in the middle of the IR. Now when going to the LLVM CodeGen, we insert branches and have multiple blocks so that means some `iree.placeholder` ops are not in the entry block anymore. I wasn't anticipating this when I wrote  `ProcessFuncInterfacePattern` so I just collected `iree.placeholder` from the entry block. It ends up after the pattern is applied we missed some `iree.placeholder` ops and that results in the generated FuncOp to be illegal.

**Comment by antiagainst** [comment]
https://github.com/google/iree/blob/3c7b05dacfdcc3a1d42fd820e6fc09563fb003b9/iree/compiler/Dialect/HAL/Target/LLVM/LLVMTarget.cpp#L138-L142

**Comment by asaadaldien** [comment]
Awesome! Debugging this toke me to a totally different route. The illegal func with some leftover iree.placeholder ops had NULL ssa values (users of placeholder ops). I still don't understand why this wasn't just failing as illegal and instead assert null value!

**Comment by antiagainst** [comment]
Dialect conversion is a bit tricky to use: it caches modifications and won't apply them until the last step. My _guess_ is here we generate an illegal func op, which triggers the framework to emit error and try to dump the old func op, which is already deleted? Some internal state might be off here.
