### ISSUE TITLE
Build failure - target 'LoopOpsTransforms' not declared 

### ISSUE THREAD

**Issue by bondhugula** [google/iree#1941]
I notice this error after an update to 89351bba213e391b22c1fa4a80963827c4d82d86. I believe that LoopOps was recently renamed and reorganized. Is this due to something broken in the build conf or a local issue in my copy? (stale dep?) I did do a blaze clean as well. 

```
$ bazel build --sandbox_writable_path ~/.ccache -c opt //integrations/tensorflow/e2e:all 
Starting local Bazel server and connecting to it...
DEBUG: /data/iree/bindings/python/build_tools/python/configure.bzl:72:9: Using python binary from PYTHON_BIN = python
WARNING: /data/uday/.cache/bazel/_bazel_uday/136ce1be51bd5797ace9540c1c80b503/external/org_tensorflow/tensorflow/core/BUILD:1785:1: in linkstatic attribute of cc_library rule @org_tensorflow//tensorflow/core:lib_internal: setting 'linkstatic=1' is recommended if there are no object files. Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
WARNING: /data/uday/.cache/bazel/_bazel_uday/136ce1be51bd5797ace9540c1c80b503/external/org_tensorflow/tensorflow/core/BUILD:2230:1: in linkstatic attribute of cc_library rule @org_tensorflow//tensorflow/core:framework_internal: setting 'linkstatic=1' is recommended if there are no object files. Since this rule was created by the macro 'tf_cuda_library', the error might have been caused by the macro implementation
ERROR: /data/uday/.cache/bazel/_bazel_uday/136ce1be51bd5797ace9540c1c80b503/external/org_tensorflow/tensorflow/compiler/mlir/tensorflow/BUILD:518:1: no such target '@llvm-project//mlir:LoopOpsTransforms': target 'LoopOpsTransforms' not declared in package 'mlir' defined by /data/uday/.cache/bazel/_bazel_uday/136ce1be51bd5797ace9540c1c80b503/external/llvm-project/mlir/BUILD.bazel and referenced by '@org_tensorflow//tensorflow/compiler/mlir/tensorflow:tensorflow_dialect_registration'
ERROR: Analysis of target '//integrations/tensorflow/e2e:train_vision_models_on_cifar' failed; build aborted: Analysis failed
INFO: Elapsed time: 18.722s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (226 packages loaded, 11583 targets configured)
```

**Comment by stellaraccident** [comment]
We'll need to wait for Geoffrey to get in to verify, but I suspect that this is due to a longstanding issue (that we are close to resolving) where our export-from-Google machinery is too automated, pushing updates without actually bumping necessary submodule versions and build files. Internally, whenever the LLVM version is bumped (which happens one to two times a day), the changes are published, but without the corresponding build bump applied to the OSS repo, we get Bazel BUILD mismatches if LLVM files moved around.

*Usually* this can be resolved by running `./scripts/git/update_tf_llvm_versions.py`, which we try to be on top of, but likely got caught unaware this time. Feel free to run the script yourself and we'll bump the version in the repo in the morning. I say that is usually all that is needed, but there is occasionally additional breakage.

**Comment by stellaraccident** [comment]
Also, we don't build the TF integrations as part of presubmit because it just takes too long. And the post-submit bot appears to have not been running recently (I think there was a quota issue). Apologies all around.

**Comment by marbre** [comment]
AFAIR post-submit actions where split into smaller chunks and are running again :)

**Comment by ScottTodd** [comment]
Post-submit appears to be passing at that commit, with coverage (though coverage is a bit sparse on that part of the tree in general).

Have you run
```
git submodule update
```
after updating to that commit?

**Comment by bondhugula** [comment]
I actually hadn't updated my submodules. Given how much bazel does, it didn't occur to me that it was to be done manually. Thanks - works fine with a submodule update.
