### ISSUE TITLE
Move iree-check-module to iree/tools/

### ISSUE THREAD

**Issue by benvanik** [google/iree#1986]
It'd be nice to keep all tools in the same place so that it's easy to find/switch between them. iree-run-module/iree-benchmark-module in iree/tools/ and then iree-check-module under iree/modules/check/ is confusing.

**Comment by GMNGeoffrey** [comment]
Yeah this comes from when the custom modules were not included in the main tooling and they all had their own opt and translate and such. I'll move it.

**Comment by benvanik** [comment]
Will be needed to get a simple deployment story (all iree-*-module tools in the same place).

**Comment by hanhanW** [comment]
Hey Ben, I'm looking for a beginner task for an intern. I think this issue is fairly simple, and could let the beginner understand more how to contribute to IREE. I'll pick this up as an example.

I think it's only for moving the iree-check-module tool to iree/tools/ and fixes BUILD and cmake files. Do you have other expected things that need to be done as well here?
