### ISSUE TITLE
HLO to LinAlg on buffers - no conversion

### ISSUE THREAD

**Issue by bondhugula** [google/iree#2011]
I have IREE as of 95eb2eb55baa696d19cfe002f74721e40d468ad7 (from May 21). On the input below, I was expecting -iree-hlo-to-linalg-on-buffers to convert the HLO ops since these ops are all covered https://google.github.io/iree/HLOOpCoverage. 

```
module attributes {tf.versions = {bad_consumers = [], min_consumer = 0 : i32, producer = 175 : i32}} {
  func @main(%arg0: tensor<5x5xf32>, %arg1: tensor<5x2xf32>) -> tensor<5x2xf32> attributes {tf.entry_function = {control_outputs = "", inputs = "Placeholder,Placeholder_1", outputs = "MatMul"}} {
    %0 = xla_hlo.multiply %arg0, %arg0 : tensor<5x5xf32>
    %1 = xla_hlo.add %arg0, %0 : tensor<5x5xf32>
    %2 = "xla_hlo.dot"(%1, %arg1) : (tensor<5x5xf32>, tensor<5x2xf32>) -> tensor<5x2xf32>
    return %2 : tensor<5x2xf32>
  }
}
```
However, running with `iree-opt - -iree-hlo-to-linalg-on-buffers` on this yields no conversion. Am I missing something?

**Comment by benvanik** [comment]
You're trying to run a specific pass used only very late in the process on a very early input form of IR; within the whole pipeline it's somewhat equivalent to trying to run an LLVM IR pass on tensor HLO ops.

Here's an example test using iree-translate at the level of IR you are trying to input:
https://github.com/google/iree/blob/master/iree/compiler/Translation/test/smoketest.mlir#L40-L51

If you want to see how to use that particular pass you can look at the lit tests that use it (and ones related to it), for example:
https://github.com/google/iree/blob/master/iree/compiler/Conversion/HLOToLinalg/test/reduce.mlir
(note that here the inputs have already been partitioned and the pass is running on just a single executable kernel and the `hal` dialect ops are present)

**Comment by bondhugula** [comment]
From this description, 
`--iree-hlo-to-linalg-on-buffers                  -   Convert from XLA-HLO ops to Linalg ops on buffers`
it appeared that this pass would convert xla_hlo dialect op into linalg on buffers, and my input is such. Strangely, there are no iree-codegen passes registered in my binary. 
```
$ iree-opt -h | grep iree-codegen
```

But:
```
iree-opt -h | grep hlo
      --hlo-legalize-to-linalg                         -   Legalize from HLO dialect to Linalg dialect
      --iree-flow-hlo-to-hlo-preprocessing             -   Apply hlo to hlo transformations for some hlo ops
      --iree-hlo-to-linalg-on-buffers                  -   Convert from XLA-HLO ops to Linalg ops on buffers
      --iree-hlo-to-linalg-on-tensors                  -   Convert from XLA-HLO ops to Linalg ops on tensors
      --iree-shape-convert-hlo                         -   Converts dynamic shape dependent HLO ops to shaped variants.
      --lhlo-legalize-to-linalg                        -   Legalize from LHLO dialect to Linalg dialect
      --hlo-legalize-to-linalg                         -   Legalize from HLO dialect to Linalg dialect
      --iree-flow-hlo-to-hlo-preprocessing             -   Apply hlo to hlo transformations for some hlo ops
      --iree-hlo-to-linalg-on-buffers                  -   Convert from XLA-HLO ops to Linalg ops on buffers
      --iree-hlo-to-linalg-on-tensors                  -   Convert from XLA-HLO ops to Linalg ops on tensors
      --iree-shape-convert-hlo                         -   Converts dynamic shape dependent HLO ops to shaped variants.
      --lhlo-legalize-to-linalg                        -   Legalize from LHLO dialect to Linalg dialect
      --hlo-legalize-to-linalg                         -   Legalize from HLO dialect to Linalg dialect
      --iree-flow-hlo-to-hlo-preprocessing             -   Apply hlo to hlo transformations for some hlo ops
      --iree-hlo-to-linalg-on-buffers                  -   Convert from XLA-HLO ops to Linalg ops on buffers
      --iree-hlo-to-linalg-on-tensors                  -   Convert from XLA-HLO ops to Linalg ops on tensors
      --iree-shape-convert-hlo                         -   Converts dynamic shape dependent HLO ops to shaped variants.
      --lhlo-legalize-to-linalg                        -   Legalize from LHLO dialect to Linalg dialect
```

**Comment by joker-eph** [comment]
> Strangely, there are no iree-codegen passes registered in my binary.

It was renamed 10 days ago: https://github.com/google/iree/commit/823fe5ace7285e5fda555ef12dbb029a130e73ef

**Comment by joker-eph** [comment]
> From this description,
> --iree-hlo-to-linalg-on-buffers - Convert from XLA-HLO ops to Linalg ops on buffers
> it appeared that this pass would convert xla_hlo dialect op into linalg on buffers, and my input is such

The pass is hard-coded to look for `hal.interface.load.tensor` and `hal.interface.store.tensor` to figure out the input/output result of the computation. 

I don't think there is any fundamental reason here to rely on these operations for the pass itself though. I agree that the coupling is making the description misleading, I don't think this coupling is necessary, but it was likely more convenient for getting the end-to-end integration in IREE faster.

**Comment by bondhugula** [comment]
> > Strangely, there are no iree-codegen passes registered in my binary.
> 
> It was renamed 10 days ago: [823fe5a](https://github.com/google/iree/commit/823fe5ace7285e5fda555ef12dbb029a130e73ef)

Got it - thanks.

**Comment by bondhugula** [comment]
> > From this description,
> > --iree-hlo-to-linalg-on-buffers - Convert from XLA-HLO ops to Linalg ops on buffers
> > it appeared that this pass would convert xla_hlo dialect op into linalg on buffers, and my input is such
> 
> The pass is hard-coded to look for `hal.interface.load.tensor` and `hal.interface.store.tensor` to figure out the input/output result of the computation.
> 
> I don't think there is any fundamental reason here to rely on these operations for the pass itself though. I agree that the coupling is making the description misleading, I don't think this coupling is necessary, but it was likely more convenient for getting the end-to-end integration in IREE faster.

Yes, there appear to be several layers of abstraction in between and this isn't clear from the pass name and most of the recent discussion at:
https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/mlir/quu_s4KMzuM/GW_6EjYFAwAJ
(although Stella initially mentioned about IREE flow and HAL). Normally, a TF MLIR user would just expect it to do HLO -> Linalg buffer, equivalent in effect to HLO -> LHLO -> Linalg.

Btw, as I mentioned earlier on that thread, I'm extracting this code out to add corresponding LHLO to Linalg buf conversions in TF proper.

**Comment by MaheshRavishankar** [comment]
What is in IREE is expected to work for IREE's use case. So there is a specific way IREE specifies buffers that are to be used as inputs/outputs of dispatch regions. These are done to make the descriptor set usage more efficient. There is also logic in there about handling dynamic shapes that is also WIP. There is some separation of concerns here. Each HLO -> Linalg method is supposed to implement an `apply` method whose arguments are the buffers to use for inputs/outputs of the converted operation.

I am all for sharing code between TF and IREE, but these would be considerations for IREE
1) We dont want to have a dependence on LHLO. HLO -> LHLO effectively has to do buffer allocation and IREE does the buffer allocation before hand. So if the HLO -> LHLO includes additional buffer allocation passes within a dispatch region (even if finally all the intermediate buffers are removed by fusion), this is a path we dont want to go down. What we are trying to do is control the ops in the dispatch region so that we can use the buffer allocated for inputs/outputs and thread them through the ops.
2) If the code is not shared and the effort is to copy the code into TF, I personally have no comments about that, but that wont address the issue of independent development, cause we will still have two separate codebases and independent evolution. I would really hope whateven is being designed here would make an effort to address IREE's use case and not add additional dependencies on LHLO.

Would it be possible to send a sketch of what is being worked out here. This is a significant change, and some heads up / design doc/RFC would be very useful. It will allow everyone to weigh in (instead of discussion on PRs or bugs)

**Comment by benvanik** [comment]
+1 to what Mahesh said. It's not a bug in IREE that an "**iree-codegen-**" pass uses IREE features and can't be copy/pasted to work elsewhere outside of IREE. I think you may have some expectations on the purity of code that you want that aren't true for good reasons, and trying to understand those reasons better before making "well couldn't you just" statements would go a long way to helping it evolve to be more flexible.

**Comment by joker-eph** [comment]
>  think you may have some expectations on the purity of code that you want that aren't true for good reasons, 

Well maybe you could start explaining these "good reasons" because it is still not clear to me right now?
For example why can't we layer these 850 lines of code so that they are in TF and reusable from there? https://github.com/google/iree/blob/master/iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp#L158-L1019

**Comment by benvanik** [comment]
Here and on the linked thread both Stella and Mahesh have done an excellent job explaining the reasons. It seems like those reasons are not being fully internalized for some reason 🤷 

The point is that we _can_ layer things but as has been pointed out several times there are things that need to be taken into consideration. If you read the comments in the code you linked you'll see that almost all of the conversions have some form of these considerations taken into account:

* the tensor->buffer mapping populated here:
https://github.com/google/iree/blob/master/iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp#L1263-L1267
is then used everywhere:
https://github.com/google/iree/blob/master/iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp#L194-L205

* since we are targeting these mapped buffers directly there's code omitted, as pointed out here:
https://github.com/google/iree/blob/master/iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp#L215-L219

* there are assumptions made by linalg that must be met, such as zeroing output prior to emitting the linalg generic op (as IREE does not guarantee buffers are zeroed upon allocation as they come from ringbuffers/pools):
https://github.com/google/iree/blob/master/iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp#L276
(and in other ops like conv)

* because we know we are going directly from tensors with value semantics there are simplifying assumptions that can be made:
https://github.com/google/iree/blob/master/iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp#L523-L528

* because we know that each reduction will only contain a single op (as we aren't performing any HLO-level reduction fusing as part of the IREE input pipeline) we can directly map to linalg variants:
https://github.com/google/iree/blob/master/iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp#L608-L615
(note, this is suboptimal, but a limitation of current linalg that we are able to paper over)

* similarly, we can make assumptions about reduction computation contents: https://github.com/google/iree/blob/master/iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp#L886-L890

* the entirety of this conversion can happen only because we know the structure of the input function is generated from a dispatch region:
https://github.com/google/iree/blob/master/iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp#L937-L984

* we can only do this because we know that the buffers cannot alias (as we start with tensors and then don't introduce aliasing ourselves):
https://github.com/google/iree/blob/master/iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp#L989-L1019

None of these are impossible to work through and some wouldn't even require much work, but something operating on LHLO will have very different assumptions (prior passes that would have been run, buffer aliasing semantics, lifetime/allocation of buffers, etc) that would make things much more complex and it's one of the many reasons why we don't use LHLO. If the goal is to copy the IREE code and adapt it to LHLO just for some other TF flow that's one thing (go for it, #yolo, etc) but if the goal is to share this code between multiple backends (including IREE) that's another. As Mahesh mentions we can't switch to using some forked version unless it actually meets our needs and meeting those needs requires understanding them.

**Comment by joker-eph** [comment]
I'm not sure why you bring LHLO into the picture... This is purely about HLO->Linalg, and there is very little into what you brought up here that seems to me making it not suitable to have a large part of the code live with HLO.

**Comment by benvanik** [comment]
It's hard to tell if you're trolling >_>

If you search the thread or this issue you'll see that Uday is talking specifically about converting to LHLO. There's a reason for that: as has also been mentioned, linalg-on-tensors is still super rough and incomplete (and may never meet all of the requirements). The conversions you linked are *not* mapping to linalg-on-tensors in most cases but linalg-on-buffers (hence the name of the file, HLOToLinalgOnBuffers.cpp). There's no generic way to do HLO to linalg-on-buffers as allocation, lifetime, and aliasing are all critical things to consider. Perhaps that's what you're not understanding?

**Comment by joker-eph** [comment]
Right above in this thread Uday wrote:

>  Normally, a TF MLIR user would just expect it to do HLO -> Linalg buffer, equivalent in effect to HLO -> LHLO -> Linalg.

Also you may have missed my email in the thread:

>  You seem to assume that because we have LHLO, we can't or won't use HLO-> "Linalg on Tensor" in any of the TF-ecosystem codegen-related project? This does not seem obvious to me though.
> If we have, for example, a good CPU codegen path upstream which starts with Linalg-on-tensors, then we'd be very happy to migrate something like tf_compile to use it.
> The only reason for LHLO to exist is to give us an anchor point with respect to XLA: on the short-term we can preserve the very robust XLA machinery for layout/buffer assignment (and other optimizations) at the HLO level and plug back into MLIR CodeGen.
> So, any codegen related handling of *HLO (and conversion from *HLO to Linalg/Affine and similar dialects) is welcome under tensorflow/compiler/mlir/xla/...

So again: "not using LHLO" isn't a discriminant for saying that conversion code between HLO and Core can't live with HLO.


>  There's no generic way to do HLO to linalg-on-buffers as allocation, lifetime, and aliasing are all critical things to consider. Perhaps that's what you're not understanding?

As far as I can tell, the conversion just requires an "oracle" to indicate which buffer to use (basically an analysis which already computed the buffer allocation as input to the conversion).
If I look at `ConvOpConversion`, it seems to me that like many other conversion it implements the `apply` method called by the parent `ConvertToLinalgBufferOp`. The logic there seems to rely exclusively on `TensorToBufferMap` to provide the precomputed buffer allocation.

I still see a decoupling here between the buffer allocator and the conversion logic (which get the buffer allocations by injection).
And guess what: this pattern [exists upstream](https://github.com/llvm/llvm-project/blob/master/mlir/include/mlir/Transforms/BufferPlacement.h#L54-L77) as well! 
This is a base class for conversion which wants to take a buffer allocator by injection to go from operations on tensor to operations on buffer.
It is used for the HLO->LHLO conversion, here is [the equivalent to the `ConvertToLinalgBufferOp` base class](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/xla/transforms/hlo_legalize_to_lhlo.cc#L109-L143) for example.
The HLO->LHLO patterns are mostly trivially 1-1 there compared to HLO->Linalg, but otherwise seems like the same overall conversion flow otherwise, isn't it?

**Comment by bondhugula** [comment]
> You're trying to run a specific pass used only very late in the process on a very early input form of IR; within the whole pipeline it's somewhat equivalent to trying to run an LLVM IR pass on tensor HLO ops

> Here's an example test using iree-translate at the level of IR you are trying to input:
> https://github.com/google/iree/blob/master/iree/compiler/Translation/test/smoketest.mlir#L40-L51
> 
> If you want to see how to use that particular pass you can look at the lit tests that use it (and ones related to it), for example:

I didn't understand this part. What I have are just xla_hlo dialect ops. I was originally saying that -iree-codegen-hlo-to-linalg-buffers isn't exactly doing what its name or its cmd-line help description says. The *-to-* passes typically legalize/convert from dialect X to dialect Y (eg. -hlo-legalize-to-lhlo, -hlo/lhlo-legalize-to-linalg, etc.) If the inputs/outputs of the ops have to be the results of hal tensor load/store operations, it isn't immediately clear to me (even now) how one should get there from the input form I have. (The iree-translate cases you link to are translating out to something completely different.)

**Comment by bondhugula** [comment]
> Would it be possible to send a sketch of what is being worked out here. This is a significant change, and some heads up / design doc/RFC would be very useful. It will allow everyone to weigh in (instead of discussion on PRs or bugs)

There's really nothing new / unexpected that's being worked out here. From all the posts on the linked tensorflow/mlir thread, it appears already clear that IREE was trying to move in a direction that allowed moving the "xla_hlo to buffer form" path to TF and MLIR proper. My short term goal is to reuse whatever code there is in IREE to complete the missing conversions via LHLO in TF proper.

**Comment by bondhugula** [comment]
> > Would it be possible to send a sketch of what is being worked out here. This is a significant change, and some heads up / design doc/RFC would be very useful. It will allow everyone to weigh in (instead of discussion on PRs or bugs)
> 
> There's really nothing new / unexpected that's being worked out here. From all the posts on the linked tensorflow/mlir thread, it appeared already clear that IREE was trying to move in a direction that eventually moved the "xla_hlo to buffer form" path to TF and MLIR proper. My short term goal is to reuse whatever code there is in the IREE conversion pass of HLO to Linalg to complete the missing conversions via LHLO in TF proper.

But the unfortunate part is that this would just lead to duplication b/w the parts you have in IREE and TF proper. So the decoupling Mehdi is suggesting between the buffer allocation and conversion logic to linalg makes sense to me - it's also inline with your roadmap/plan mentioned on that thread. I already noticed a few issues in the conversion part of the conv op, and if it's just copied over for  LHLO to Linalg one would have to maintain/fix both separately (in IREE and in TF proper) to make progress.

**Comment by MaheshRavishankar** [comment]
Could you provide more details on what the issue with the conv op was? We have lit tests that verify correctness of the generated code for conv ops. Maybe its a configuration we have missed (the xla_hlo.conv operation seems to support many different configurations, mich more than what Linalg supports natively.

> So the decoupling Mehdi is suggesting between the buffer allocation and conversion logic to linalg makes sense to me - it's also inline with your roadmap/plan mentioned on that thread. 

I am not sure I follow what you are saying here. If I read what Mehdi is saying the decoupling is already happened. There base class that all the conversion patterns inherit from does the figuring out of what buffers to use for the inputs and outputs. All the apply methods are fairly hermitic in the sense that they just use those buffers. So some refactoring of the class heirarchy or just a bunch of utility methods created from the apply methods here should work. The reason to have the `apply` method is specifically to decouple the conversion from having to reason about "which buffer to use".

**Comment by bondhugula** [comment]
> Could you provide more details on what the issue with the conv op was? We have lit tests that 

I'm going to be creating a separate issue for this. 

verify correctness of the generated code for conv ops. Maybe its a configuration we have missed (the xla_hlo.conv operation seems to support many different configurations, mich more than what Linalg supports natively.
> 
> > So the decoupling Mehdi is suggesting between the buffer allocation and conversion logic to linalg makes sense to me - it's also inline with your roadmap/plan mentioned on that thread.
> 
> I am not sure I follow what you are saying here. If I read what Mehdi is saying the decoupling is already happened. There base class that all the conversion patterns inherit from does the figuring out of what buffers to use for the inputs and outputs. All the apply methods are fairly hermitic in the sense that they just use those buffers. So some refactoring of the class heirarchy or just a bunch of utility methods created from the apply methods here should work. The reason to have the `apply` method is specifically to decouple the conversion from having to reason about "which buffer to use".

That's still not what I meant by decoupling. A decoupling would allow you to place the conversion from the buffer form into Linalg in TF repo proper and have it reused by LHLO to Linalg. Perhaps it's easy for you / other authors of these pieces to see how this is achieved, and having a single reference/example migrated to such a form would help other contributors.
