### ISSUE TITLE
A link in documentation hub doesn't work

### ISSUE THREAD

**Issue by hanhanW** [google/iree#2029]
There is a "getting started guides" link in https://google.github.io/iree/GetStarted/Python, and it doesn't redirect to correct url, i.e., got a 404 not found page. It's redirected to `https://google.github.io/iree/GetStarted/` and I think the last `/` should be removed to make it work.

**Comment by ScottTodd** [comment]
This is trickier than it appears, since the source is just
```
You should already have IREE cloned and building on your machine. See the other
[getting started guides](.) for instructions.
```
the trailing slash insertion is something within Jekyll, and GitHub pages handling of trailing slashes is fixed.

**Comment by antiagainst** [comment]
Ouch. Yes, also reported here: https://stackoverflow.com/questions/54727643/trailing-slashes-in-jekyll-github-pages-site-cause-404. So if you start the website locally with `bundle serve` everything is fine. I wonder maybe `(../GetStarted)` could work? Otherwise let's just remove the link. It's not really worth the time for this small issue. :)
