### ISSUE TITLE
third_party/dawn is missing

### ISSUE THREAD

**Issue by marbre** [google/iree#214]
The components in `iree/hal/dawn` depend on `third_party/dawn`. However, Dawn was not yet added as a submodule to the repository.

**Comment by ScottTodd** [comment]
Duplicate of #11 

The upstream project (https://dawn.googlesource.com/dawn) uses the Chromium build system, but we have a Bazel build configured internally which I was using. That Bazel setup could be migrated here to IREE under `build_tools/third_party/`, and we could also see about adding a CMake build here or upstream. Since it's going to take more work to get `iree/hal/dawn` actually doing interesting things, I've been putting off making the build more accessible.

**Comment by marbre** [comment]
Sorry, missed the original issue.

I would rather prefer to see a Bazel or a CMake build configuration upstream. As an intermediate step it would also help in the IREE repo, but as you mentioned, that depends on how important the `iree/hal/dawn` components are at the moment.

**Comment by ScottTodd** [comment]
Duplicate of #11

**Comment by ScottTodd** [comment]
Why GitHub couldn't parse that from my original comment is beyond me...
