### ISSUE TITLE
Multi-GPU distribution support

### ISSUE THREAD

**Issue by yzhang93** [google/iree#2168]
Hello,

I'm new to iree, and just went through all tutorials and tests. I'm interested in keras model training using iree similar to keras_model_train_test.py. And I have some related questions

1. Do you have multigpu distribution supported?
2. What is 'tf' backend? Is it the only backend supported for e2e training?

Thanks for your response in advance!

**Comment by ScottTodd** [comment]
Hi! Thanks for the question. There are a few things to unpack here, which could benefit from some extra documentation in the README or on our website.

For more background on our thoughts on "training" in IREE, see @stellaraccident 's comment [here on our mailing list](https://groups.google.com/d/msg/iree-discuss/9FqHtLAyn_8/vOw59jr7BgAJ).

@rybakov recently added [keras_model_train_test.py](https://github.com/google/iree/blob/master/integrations/tensorflow/e2e/keras/train/keras_model_train_test.py) as a place for us to test and develop support for training. The "tf" backend is the full TensorFlow system (see [this README](https://github.com/google/iree/tree/master/integrations/tensorflow/e2e)). The test only runs on that backend right now, since there are missing pieces in the lowering from TF -> SavedModel -> IREE -> various IREE backends. @silvasean has also been working on triaging the issues there. (We can and should move some of those discussions onto GitHub)

As for multi-gpu, we're definitely planning on supporting heterogenous inference (e.g. CPU + GPU + TPU cooperating for a single workload) in various ways. From what I understand, IREE's core design has been set up to support those cases, but there is still substantial work across the stack to fully realize it (for example, see [device placement on the roadmap](https://google.github.io/iree/DesignRoadmap#device-placement), cc @benvanik). Hopefully any work there will support both heterogenous/distributed inference and training, but see Stella's comment for some of the caveats there - we expect that TensorFlow and other libraries will still be the place for the support mechanisms like file IO, tf.data, etc.

**Comment by stellaraccident** [comment]
+1 to what Scott says. Training support in IREE is nascent, and the reason it is only enabled on the "tf" backend is because nothing there works on the native IREE backends yet.

In general, the mental model that may make sense to apply is that IREE exists at the lower levels of the stack where you want compilation support to help you integrate with your devices (we explicitly target smaller scale devices and deployments). For general purpose, high-end training, the new TensorFlow runtime is being designed around similar technology at the next layer up, and is likely to be the entrypoint for people wanting to run more classic distributed training workloads. Neither IREE nor TFRT are ready for real users yet (unless if you are looking to contribute and are ok with the bleeding edge).

At an appropriate time, we will likely layer IREE under TFRT as a gateway to more standard ML workloads/users. In such a scenario, IREE will continue to directly serve people who want to do controlled deployments with AOT compilation to supported CPU and GPU targets, but it is not trying to be a solution for everyone (and will integrate with the other parts of the ecosystem to meet people with higher level use cases).

**Comment by benvanik** [comment]
(hope that helped, feel free to ask more questions or reopen if you want to talk more about these topics!)
