### ISSUE TITLE
Define initial SIMD dialect

### ISSUE THREAD

**Issue by benvanik** [google/iree#24]
Starting from the [WebAssembly SIMD proposal](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md) define an MLIR dialect with the appropriate types (v128) and ops.

**Comment by bhack** [comment]
Do you plan to explore also long vectors https://github.com/WebAssembly/simd/issues/29?

**Comment by nicolasvasilache** [comment]
We have a bunch of stuff in flight regarding these topics that generalize quite nicely.
If this is an active area of interest, I'd encourage you to look at what we are doing on the MLIR Vector dialect: https://mlir.llvm.org/docs/Dialects/Vector/ and ask questions.
We also discussed with ARM folks re MLIR and how to model SVE in a very specific way using regions because of the peculiar constraints of SVE (i.e. it's not "just" `vector<?x?xf32>`).

cc @tetuante

**Comment by bhack** [comment]
Thanks for the reference 
/cc @kasanovic @aswaterman if they are interested for the RISC-V V extension (now that also @lattner is in SiFive).
