### ISSUE TITLE
Command queue CTS tests failing for Adreno GPUs

### ISSUE THREAD

**Issue by antiagainst** [google/iree#2907]
See https://buildkite.com/iree/iree-android-arm64-v8a/builds/908#995e8735-2dfd-4937-90b0-7bd8c4cafd44:

```
[ RUN      ] AllDrivers/CommandQueueTest.BlockingSubmit/vulkan
I ../iree/hal/cts/cts_test_base.h:88] Reusing existing driver 'vulkan'...
I ../iree/hal/cts/cts_test_base.h:66] Creating default device...
I ../iree/hal/vulkan/vulkan_driver.cc:295] Created Vulkan Device: Adreno (TM) 640
I ../iree/hal/cts/cts_test_base.h:68] Created device 'Adreno (TM) 640'
../iree/hal/cts/command_queue_test.cc:73: Failure
Value of: command_queue->Submit( {{}, {command_buffer.get()}, {{semaphore.get(), 1ull}}})
Expected: is OK
  Actual: INTERNAL: VK_ERROR_INITIALIZATION_FAILED (of type iree::Status), which is not OK
F ../iree/hal/vulkan/emulated_timeline_semaphore.cc:56] Check failed: outstanding_semaphores_.empty() Destroying an emulated timeline semaphore without first waiting on outstanding signals
Aborted 
```

This is likely an Andreo specific issue. I suspect it's because we are submitting empty command buffers.

**Comment by ScottTodd** [comment]
The CTS tests have changed a bit since this was filed: https://github.com/google/iree/tree/main/iree/hal/cts

command_queue_test no longer exists, but the same behavior may be exercised in a different test, such as:

https://github.com/google/iree/blob/da64c93eb38fe6864b9ebeb3674e6229fa4dae1b/iree/hal/cts/semaphore_test.cc#L99-L117
https://github.com/google/iree/blob/da64c93eb38fe6864b9ebeb3674e6229fa4dae1b/iree/hal/cts/semaphore_test.cc#L186-L207

**Comment by antiagainst** [comment]
This is not an issue anymore: https://source.cloud.google.com/results/invocations/10b72b6f-6447-40e6-9d9a-0f61cc7d7215/targets/iree%2Fgcp_ubuntu%2Fcmake%2Flinux%2Fx86-swiftshader%2Fpresubmit/log.
