### ISSUE TITLE
Dump input values to a file

### ISSUE THREAD

**Issue by hanhanW** [google/iree#3106]
We are able to dump MLIR input files to artifact_dir, ie /tmp/iree/modules/.../iree_input.mlir

It would be good if we can also dump the input values to the same place, (maybe can name as iree_input_values_X.txt), so we can feed those input data to IREE tools easier.

An idea is to call `tf_utils.save_input_values([src_inputs, paddings], debug_dir)` when a binding function is invoked. The method will generate a proper input file that can be used in IREE tools.

**Comment by phoenix-meadowlark** [comment]
The inputs for each unittest are being stored in an IREE ingestible format in `.../<module_name>/<backend>/traces/<unittest_trace>/flagfile` as the `--inputs` flag. 

Since absl lets you pass flagfiles to modules regardless of whether or not the module uses all of the flags in a flagfile, you should be able to pass this flagfile to any of IREE's tools that use the `--inputs` flag. Does this satisfy your use case?

For example, you could pass the inputs to `iree-run-module` like this:

```shell
bazel run iree/tools:iree-run-module -- \
  --flagfile=/tmp/iree/modules/ResNet50/cifar10/iree_llvmjit/traces/predict/flagfile \
  --<run-module specific flags>...
```

**Comment by hanhanW** [comment]
Does this only work for `bazel`? How can I use it with the binary built by cmake?

**Comment by phoenix-meadowlark** [comment]
From what I understand Abseil flags should work just as well with cmake as with bazel? This is just using an Abseil feature, so I'd imagine it wouldn't matter if cmake or bazel were used to build IREE's binaries.

**Comment by hanhanW** [comment]
I think there is an issue, run_mlir_main is not using absl flags. It is using llvm::cl instead.

But yes, this works with other tools. thanks!
