### ISSUE TITLE
Allow iree-run-mlir usage without manual shape input

### ISSUE THREAD

**Issue by rybakov** [google/iree#3175]
I have to specify all shapes of input data for example: /tools/iree-run-mlir -iree-hal-target-backends=vmla ~/test.mlir -input-value='2x4x4x3xf32=0' --input-value='2x3xf32=0'....

The problem: in some cases the number of inputs is large I have to specify all of them manually, plus need to keep track both number of inputs with their shapes.

It would be great if iree-run-mlir can read shape of the input data from mlir file itself and feed zero data automatically for a case when "input-value" is not specified. 

In case when shape is dynamic and "input-value" is not specified then it should crash with message that input with dynamic shape has to be specified.

**Comment by benvanik** [comment]
For the zero-initialized case in particular I think we can support that with optional trailing arguments (similar to `*args` in python), however the support required to fully model arbitrary python calling with sparse argument lists is not something we'll be able to match in the native tools. The work to add numpy npz support should make it easier to construct inputs to the tools as you can just save off your arguments with `numpy.savez([your ndarrays])` and pass that file to iree-run-module/iree-run-mlir and otherwise you can specify things manually. #5707 will add initial npy/npz support.

**Comment by benvanik** [comment]
Closing in favor of the feature in #9453 that will support this.
