### ISSUE TITLE
Integrate mlir-hlo repository

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#3312]
The mlir-hlo repository creates the possibility of depending on HLO without TF.

Probably requires a Googler to start out with because we need to get the Bazel build files exported. They're already exported in TF, but aren't to the separate repo.

This blocks https://github.com/google/iree/issues/3311

**Comment by GMNGeoffrey** [comment]
Actually I missed that the CMake build is still using mlir-hlo from the tensorflow submodule

@marbre @phoenix-meadowlark Can you coordinate between this and #4009 and #4250 on getting the CMake build to use the mlir-hlo submodule? The Bazel build is switched over with #4450. I can also take a look, but seems like the work has already been done and just needs to be cleaned up a bit. Thanks!

**Comment by marbre** [comment]
Since, the required changes are quite straight forward, I simply sent #4501 to address this.

Switching over to the native mlir-hlo CMake targets is more tricky if we don't want to set include directory on a global level. Thus, #4409 needs more attention but is fortunately not required to switch over to the mlir-hlo submodule.
