### ISSUE TITLE
Fix `NDEBUG` unsetting issue

### ISSUE THREAD

**Issue by antiagainst** [google/iree#3380]
From @benvanik: 

RelWithDebInfo should set NDEBUG [by default](https://cmake.org/gitweb?p=cmake.git;a=commit;h=0ddfc51f6a68c61d84b5b4818b32ecbf755a949a). I think there's something (LLVM?) unsetting it. We really need to fix that - it's very unexpected behavior (and would break anyone integrating IREE into their project that is assuming the default cmake behavior of RelWithDebInfo/Release sets `NDEBUG`).

**Comment by benvanik** [comment]
I touched this in #3370 but forget if this was a followup for that or dupe. Needs investigation.

**Comment by okkwon** [comment]
Looking into it

**Comment by okkwon** [comment]
Disabling IREE_ENABLE_ASSERTIONS causes a build failure due to a PDL code. (PatternMatch.h:1100)

After guarding the problematic code with `not defined(NDEBUG)`, the compilation error went away, but now I got this error:

[968/1146] Generating simple_mul.h, simple_mul.o, simple_mul.vmfb
FAILED: samples/static_library/simple_mul.h samples/static_library/simple_mul.o samples/static_library/simple_mul.vmfb /usr/local/google/home/okwan/iree/build/samples/static_library/simple_mul.h /usr/local/google/home/okwan/iree/build/samples/static_library/simple_mul.o /usr/local/google/home/okwan/iree/build/samples/static_library/simple_mul.vmfb 
cd /usr/local/google/home/okwan/iree/build/samples/static_library && /usr/local/google/home/okwan/iree/build/tools/iree-compile --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=dylib-llvm-aot --iree-llvm-link-embedded=false --iree-llvm-link-static --iree-llvm-static-library-output-path=simple_mul.o /usr/local/google/home/okwan/iree/samples/static_library/simple_mul.mlir -o simple_mul.vmfb
malloc(): corrupted top size

**Comment by okkwon** [comment]
I had to turn off LLVM_ENABLE_ASSERTIONS=OFF too. Need to double check with a fresh build.
