### ISSUE TITLE
Metal related code is not built with Bazel

### ISSUE THREAD

**Issue by freedomtan** [google/iree#3742]
It seems Metal backend related code is not built when building with Bazel.

**Comment by freedomtan** [comment]
I have a work-in-progress patch that can enable building them with Bazel

**Comment by antiagainst** [comment]
Hi @freedomtan, yes the Metal HAL driver can only be built with CMake at the moment. If you are willing to contribute to that, it would be truly awesome!

With that said, there are a few technical issues we need to address to make sure everything is on a solid foundation. I'm not an expert on Bazel, so my colleague @GMNGeoffrey and @ScottTodd can share more thoughts. In general, I think the big questions to sort out are 1) conditional compilation and 2) differences between Bazel and Blaze (Google internal version) and how to handle them. I think 2) is mostly on us. I'm wondering your thoughts on 1).

Also curious, is there a compelling reason that you need Bazel on macOS?

**Comment by ScottTodd** [comment]
I dropped a few comments on https://github.com/google/iree/pull/3743

Where practical, we've been trying to keep build system complexity down. Supporting all configurations on all platforms is nice, but it takes time to set up and maintain. If enough users want a configuration/platform combination then we'll consider it :D. We were somewhat expecting that more open source users would want to use CMake over Bazel.

As Lei points out, there are a few details to work through on conditional compilation and open source / internal differences, but a few of us have already solved those problems before on other projects.

I think we could proceed with Metal support if it would be useful enough to you/others. I would put it in the "unsupported" category around with the rest of macOS for now though (https://google.github.io/iree/get-started/getting-started-macos-bazel), since we don't have continuous integration running on it and not many core team members have even tried it.

**Comment by benvanik** [comment]
+1 to verifying that anyone wants it first. As far as I know, no one but google (internally) really uses bazel for iOS deployments.

**Comment by GMNGeoffrey** [comment]
Well it seems like at least one person wants it :-) As others said, we had been anticipating that there would be minimal open source interest in a Bazel config and the configuration for it with the internal version of Bazel is sufficiently different that it complicates things. But if you can get it to work without interfering with the rest of the build, I'm pro adding it :smile:

**Comment by freedomtan** [comment]
Thanks for all comments. I'll continue improve #3743.

@antiagainst We have some TensorFlow/TFLite based codebases. So, using Bazel is a natural solution. I think conditional compilation, as @ScottTodd mentioned in comments of #3743, could be addressed with proper `bazel select()` unless you don't like it. To me, it's kinda like `#if define` in C.

**Comment by freedomtan** [comment]
close this since #3743 is merged
