### ISSUE TITLE
Rework HAL CTS to use the C API

### ISSUE THREAD

**Issue by benvanik** [google/iree#3934]
It currently is using C++ types directly, which reduces its usefulness with respect to testing the HAL and documenting its usage. It's also blocking porting portions of the HAL to C which is required to allow external user-provided HAL backends.

This isn't urgent but if left too long the CTS will likely need to be deleted until one using the C API can be written (it's not providing enough value in its current form relative to unblocking out-of-tree HAL drivers). A CTS against the C API would be extremely valuable for developers of out-of-tree drivers (as well as for ensuring good coverage of the C API for us), so it's definitely good to get a plan in place to fix it up.

**Comment by benvanik** [comment]
As we are likely to be making more changes to the HAL during the Q1 having a CTS (or using it as an excuse to flesh one out) would be useful to ensuring that we are working correctly across metal and vulkan (and webgpu and such).

**Comment by ScottTodd** [comment]
It would also be nice to rework the gtest setup so that out of tree drivers can run against the same set of tests, or the list of drivers to test against could be controlled more easily. The current

```
INSTANTIATE_TEST_SUITE_P(
    AllDrivers, AllocatorTest,
    ::testing::ValuesIn(testing::EnumerateAvailableDrivers()),
    GenerateTestName());
```

style setup is pretty constrained in how it runs and the output isn't as useful as it could be when different drivers are mixed together test case by test case.
