### ISSUE TITLE
Pick a target model from the list of supported TFLite GPU models.

### ISSUE THREAD

**Issue by benvanik** [google/iree#3953]
There's a helpful list of the 4 models TFLite GPU supports here, including downloads of serialized tflite flatbuffers: https://www.tensorflow.org/lite/performance/gpu#supported_models_and_ops

We should pick one of these as our starting point and intentionally not try to build from source - if this is what they are telling users to download and use as a deployable it's something we should be able to import. Given these 4 models are almost all identical in terms of op composition it we can choose based on whatever is either coolest, most well-supported by our current optimization strategies, or just throw darts.

**Comment by bjacob** [comment]
@mariecwhite recommended MobileNet SSD as the most relevant workload among the ones listed there.

**Comment by benvanik** [comment]
Cool! We can then do a first-pass analysis to see which TOSA ops in particular we need (so importing the tflite flatbuffer into MLIR and lowering to the TOSA dialect via the PR sitting in tensorflow with the tool). That's tracked in #3949, so we can update this issue with what we find once one of us checks out the PR and runs it.

**Comment by sjarus** [comment]
Apologies for the unsolicited input - we have internally run SSD Mobilenet V2 and V3 (and a few dozen more full networks) through the internal TOSA regression infrastructure. V2 passes with a bit exact match when running the TOSA form using the TOSA [reference model ](https://git.mlplatform.org/tosa/reference_model.git/about/) vs TFLite original output. The V3 version matches almost exactly, to within +/-1 in some elements due to an issue we identified in tfl.hardswish. It was raised in https://github.com/tensorflow/tensorflow/issues/40781 .

**Comment by bjacob** [comment]
Thanks for bringing tensorflow/tensorflow#40781 to my attention, I replied there. +/- 1 differences are fine.

**Comment by benvanik** [comment]
@sjarus very very welcome input! We're very excited to start plumbing things through! 👨🏼‍🔧

**Comment by sjarus** [comment]
Thanks for your feedback @bjacob and @benvanik ! Of the four networks listed in the link in the first post, we've already run all but PoseNet, which is new to us.
