### ISSUE TITLE
Consider switching cmake CI to ninja

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#489]
So I just tried out using ninja for the cmake build instead of the default make. It is waaaay faster than a normal cmake build. I was planning to look into using goma for distributed builds and result caching. Maybe we should consider ninja as well/instead? It's certainly much easier to implement that change.

**Comment by antiagainst** [comment]
+100 for ninja!

**Comment by GMNGeoffrey** [comment]
Just as a data point, the cmake build take 2.5 minutes on my workstation with ninja, compared to 14 minutes with make. That could make the cmake build fast enough to run on presubmit again (I still have to move it to Kokoro for irritating reasons to do with GitHub's different status/checks APIs)

**Comment by GMNGeoffrey** [comment]
It looks like the GitHub default VMs don't have ninja though, so probably want to move the build to kokoro first anyway.

**Comment by antiagainst** [comment]
That's interesting, but not very surprising. I'm not familiar with GitHub actions. We used to use Appveyor and Travis CI for SPIR-V projects. They don't have ninja by default either. Back that time we basically download the ninja binary from https://github.com/ninja-build/ninja/releases.

**Comment by GMNGeoffrey** [comment]
Yeah I can download it as part of the action, but we kind of have to switch of GitHub actions for CI anyway and they're real annoying to change because there's no way to interactively access the VMs so every change for installing software requires a push and starting a new VM... Also their status badges are broken. Overall not impressed with them as a CI tool, although they're nice for automation (and then we run into their auth model that totally breaks if contributors are on forks...)

**Comment by GMNGeoffrey** [comment]
@marbre, since you've been doing a lot of work on the cmake build. How do you feel about ninja?

**Comment by marbre** [comment]
Thank you for asking about my opinion :) The short answer is, yes we can let CMake generate ninja files.

The long answer is that I don't have a strong opinion. The MLIR [Getting Started](https://mlir.llvm.org/getting_started/) guide assumes you have ninja and the LLVM [Getting Started](https://llvm.org/docs/GettingStarted.html#getting-the-source-code-and-building-llvm) docs comments on the common generators  "Ninja — for generating Ninja build files. Most llvm developers use Ninja." So ninja is absolutely fine. To comment on

> Just as a data point, the cmake build take 2.5 minutes on my workstation with ninja, compared to 14 minutes with make. That could make the cmake build fast enough to run on presubmit again (I still have to move it to Kokoro for irritating reasons to do with GitHub's different status/checks APIs)

that is the point where I'm afraid I cannot agree. I assume that after generating Makefiles, you build by using `cmake --build .` or `make`. This does not trigger a parallel build, since make's default is to use a single instance. If you want to build in parallel you have to specify the number of jobs. On the server with 20 cores, to which I have access, the commands would be `make -j20` or rather `cmake --build . --parallel 20`. In contrast, ninja builds in parallel by default.
Anyway, generating ninja files and performing the build with ninja is a little bit faster than generating Makefiles and using make for compiling:

**make**
```bash
time CC=clang-8 CXX=clang++-8 cmake -DCMAKE_BUILD_TYPE=Debug ..
real    1m4.352s
user    0m43.368s
sys     0m21.004s

time make -j20
real    1m53.479s
user    24m58.866s
sys     1m32.153s
```

**ninja (default)**
```bash
time CC=clang-8 CXX=clang++-8 cmake -DCMAKE_BUILD_TYPE=Debug -GNinja ..
real    0m59.139s
user    0m40.204s
sys     0m18.965s

time ninja
real    1m37.482s
user    24m40.962s
sys     1m28.346s
```

By default ninja is running 22 jobs in parallel, which I was told by `ninja --help`:

```
-j N     run N jobs in parallel [default=22, derived from CPUs available]
```

However, timing does not changes significantly, if the number of parallel jobs is limited to 20:

**ninja (20 jobs)**
```bash
time ninja -j 20
real    1m37.429s
user    24m37.701s
sys     1m23.626s
```
So finally, yes, let's go with Ninja, but don't expect such a huge speedup.

**Comment by GMNGeoffrey** [comment]
Yeah that is of course an unfair comparison, since I was running make single-threaded. That's how we're running it in the CI too though. So in that sense switching to ninja should also generate a speedup, but only because I configured make terribly :-D Like I said before, I'm very new to CMake. I didn't realize this whole time I've been running my builds single-threaded... So yeah, passing -j 14 to the make build (same as ninja uses on my machine), I get a similar performance (although ninja is still a hair faster).

So yeah, we could certainly just put some parallel option in the cmake build script and get a similar speedup. I think it's probably nicer to use Ninja though, since then we don't have to hard-code the number of jobs and everyone can run the same script for good performance. If MLIR and LLVM both expect Ninja, I think it's reasonable that we use it as well. People can still build it with make if they want.

But regardless this seems like we can run the cmake build on presubmit again and I can put off figuring out how to set up a goma instance for a while longer :-D

**Comment by marbre** [comment]
Well instead of determining the number of available cores, just let's switch to ninja in the CI :+1: 

In addition we should also add this to the [docs](https://github.com/google/iree/blob/master/docs/getting_started_on_linux.md#build-1). Maybe even mentioning the alternative to generate "Unix Makefiles" together with a note that `cmake --build` runs a single instance if not specific otherwise :wink:

**Comment by GMNGeoffrey** [comment]
> Well instead of determining the number of available cores, just let's switch to ninja in the CI 
> 
> In addition we should also add this to the [docs](https://github.com/google/iree/blob/master/docs/getting_started_on_linux.md#build-1). Maybe even mentioning the alternative to generate "Unix Makefiles" together with a note that `cmake --build` runs a single instance if not specific otherwise

Yup. That's the plan :-)

**Comment by GMNGeoffrey** [comment]
@marbre Is the existence of the github action for cmake at all useful to you? I'm inclined to delete it when I have the Kokoro (which is basically our internal instance of Jenkins) presubmit set up.

The nice thing about the GitHub actions is that if you keep the actions basic they "just work" for everyone even on forks. The annoying thing is that they are not very customizable and their auth system means it's impossible to have presubmits contact external services.

Kokoro allows us way more customization at the cost of more setup, but it also only auto-triggers builds for organization members and collaborators and otherwise requires someone with write access to apply the "kokoro:run" tag (to avoid giving people RCE).

I figure that since the cmake build on that little 2-core GitHub VM is so slow (even with Ninja, I think it's not going to be great) that it's not really that useful. But we can keep the action around if it's useful for you.

Another note is that I tried out Ninja on our current 4-core Kokoro build VMs and the build ran in 13 minutes (the full script with submodule cloning). That's alright, but still a little slow, I think. I spun up a 32-core VM for fun and that got it down to 3. I may try out that as a simpler alternative to setting up goma.

**Comment by marbre** [comment]
Thanks for asking. Actually I am not 100% sure, so I just share my thoughts. I build and test locally. At the moment I think I don't require GitHub actions, didn't even noticed that it works for forks ;D However, having a test pipeline at  some later stage might be nice, and I think that is when GitHub actions might come into the game again (?). To build IREE, I do not require a pipeline at all. What would be useful at a later point in time is a test pipeline, if the time consumed by tests increases or if there is something I cannot test locally. Especially for the test pipeline, it would be nice to get feedback ASAP and not having to wait for someone who has to manually trigger the pipeline. No need to work with forks in general, but something running automatically on PRs would be helpful. If GitHub actions are hard to customize, a test pipeline triggering a GitHub VM probably also wont be able run tests I cannot execute locally. Further, the compute power might probably will be a limiting factor. Seems like GitHub actions can be dropped?

**Comment by GMNGeoffrey** [comment]
Yeah I think the GitHub actions are going to be unlikely to execute anything you can't do locally. Since you're not using it, let's delete it for now and we can solve the problem of automatically triggering CI on PRs from external contributors when it actually becomes an issue. I'll finish getting the Kokoro presubmit set up and then I'll delete the GitHub action.
