### ISSUE TITLE
Improve error messages when build tools are missing

### ISSUE THREAD

**Issue by bjacob** [google/iree#4892]
Currently, making an Android build without defining `IREE_HOST_BINARY_ROOT` results in an error like this:

```
[215/376] Generating flatcc_reader.h, flatcc_builder.h, flatcc_verifier.h, flatcc_json_printer.h, flatcc_json_parser.h
FAILED: iree/base/flatcc_reader.h iree/base/flatcc_builder.h iree/base/flatcc_verifier.h iree/base/flatcc_json_printer.h iree/base/flatcc_json_parser.h 
cd /usr/local/google/home/benoitjacob/iree/iree/base && /bin/iree-flatcc-cli -o /usr/local/google/home/benoitjacob/iree-build-android-2/iree/base -I /usr/local/google/home/benoitjacob/iree --reader --builder --verifier --json flatcc.fbs
/bin/sh: line 1: /bin/iree-flatcc-cli: No such file or directory
```

The strange-looking `/bin/...` paths are actually expanded from "${IREE_HOST_BINARY_ROOT}/bin/..." , [here](https://github.com/google/iree/blob/main/build_tools/cmake/iree_macros.cmake#L119).

An error message in that cmake macro could help. It should point out that it is currently required not only to have made a host build, but also to have *installed* it  (seeing how it wants the path to contain `/bin/`.)

**Comment by ScottTodd** [comment]
Also take a look at `add_executable` with `IMPORTED` (see [this](https://discord.com/channels/689900678990135345/689957613152239638/809282260641644565) Discord comment). CMake docs: https://cmake.org/cmake/help/latest/command/add_executable.html#imported-executables.

That would be used instead of (or in conjunction with) https://github.com/google/iree/blob/5c5b62e3b72c677aa04479426c41b81bbcc1228e/build_tools/cmake/iree_macros.cmake#L115-L126
