### ISSUE TITLE
The lowering of ConcatenateOp to Linalg on tensors causes a redundant linalg.fill op

### ISSUE THREAD

**Issue by hanhanW** [google/iree#4985]
In https://github.com/google/iree/pull/4954, the concatenate op is lowered to

```
%0 = linalg.init_tensor ...
%1 = linalg.fill(%0, %cst) ...
%2 = subtensor_insert %in1 into %1[...][...][...]
%3 = subtensor_insert %in2 into %2[...][...][...]
%4 = subtensor_insert %in3 into %3[...][...][...]

compute_with (%4)
```

Different from pad op, concatenate doesn't pad any value, so the `linalg.fill` is not needed. However, there is no a clean way to represent concatenate op in Linalg on tensors. The approach with bunch of subtensor_insert needs a placeholder, or the first subtensor_insert won't have a dest tensor to insert. This will cause an extra redundant fill after bufferization.

There are other options for lowering concatenate op. For more details, see https://llvm.discourse.group/t/rfc-linalg-add-concatenate-operation-to-linalg/2879

**Comment by benvanik** [comment]
There are two things that will help this - how they intersect still needs some work though.

The best thing to do is - when possible - turn these into `flow.tensor.update` ops instead of putting them in dispatch regions. Note that this only works for contiguous updates today (Mahesh found this out the hard way yesterday - sorry! :). By doing this the allocator will place the outputs of the ops feeding into the concat into the right memory to start such that there are no copies involved at all. The producing linalg ops will be producing the `%inN`'s right into the final concatenated memory.

What `flow.tensor.update` does is not entirely special though - it's just an in-place scatter operation. I'll be adding support this week to enable `flow.dispatch.workgroups` to do the same thing (#4898). This will enable `flow.tensor.update` to turn into a `flow.dispatch.workgroups` for performing the scatter when non-contiguous and do so in-place with only one copy (from the producers into the consumer) but O(updates) vs O(target). For dispatches that have subtensor_inserts in them they will be able to directly write into the inputs - that's the ideal case. If there were a `flow.tensor.concat` (mapped from a `linalg.concat` as proposed above) then it could do the same thing: if the concat can be turned into a set of `flow.tensor.update`s (one per tensor being concatenated) because the inserts are contiguous then that's the fastest path (direct placement into memory), falling back to the dispatch performing the in-place updates such as when non-contiguous or fully dynamic. The awesome thing about this approach is that it propagates optimizations: if several of the input tensors to the concat can be made contiguous then they'll be placed right into an intermediate that gets scattered in one go - it's just a few canonicalizers.

So I think once I get this in @MaheshRavishankar will start to make use of it for pad (which has similar in-place requirements) and we could also extend it to concats (doing the naive thing to start). It's then just an optimization to turn the concats into `flow.tensor.update` or a potential `flow.tensor.concat` that will save memory/reduce copies.

**Comment by MaheshRavishankar** [comment]
Both the pad lowering and the concat lowering use `subtensor_insert`. There is a simple pattern that allows you to lower from `subtensor_insert` to `flow.tensor.update`. The pattern needs to check
1) All inner offsets are zero.
2) For the offsets that are zero the size of the source/update is the size of the dest/target.
So this pattern would work for both pad and concat.
We could do a similar thing for fill, where when possible fill can be mapped to a flow operation.

But all this needs PR #4983  to land

**Comment by benvanik** [comment]
Yep! There's currently a `flow.tensor.splat` that can be used for non-in-place fills (which then translate into DMA fill operations), and as part of the #4898 work we can add a `flow.tensor.fill` that does the operation in-place (for some contiguous range within the tensor). Scatters then still fallback to the dispatch route.

For small non-contiguous cases we can still use these ops just by unrolling (or scf.for'ing) them. This is a balance: a dispatch doing a scatter of 4 contiguous subspans will be less efficient than 4 DMA operations (as we may be able to fold the 4 operations away entirely and just place the outputs there), while a dispatch doing a scatter of 4000 dynamic subspans will be much more efficient than 4000 DMA operations. In many cases of these insertions I've seen in the past there are only a few values though in dynamic cases we just can't know. The advantage is that we can insert flow control and conditionals; so in dynamic cases where we can't statically determine that the ranges are contiguous (which is still sometimes possible with dynamic shapes, so long as the SSA values match) we can just emit an scf.if that switches between the DMA case and the dispatch case.

All of those are just optimizations, though, and since we know we'll need both the DMA path and the dispatch path we can start there and improve the mix/selection over time after #4983 and #4898 land. Those will be fun optimizations to add :)

**Comment by hanhanW** [comment]
Yes, Mahesh and I had a discussion yesterday, and we agreed that subtensor_insert issue will get resolved with the patch.

I think the issue of the extra fill is that we don't have `linalg.concat`. In pad op, we have `linalg.pad_tensor` which will produce a tensor:

```mlir
func @pad_tensor_static(%arg0: tensor<12x4xf32>, %arg1: tensor<f32>) -> tensor<18x12xf32> {
    %c4 = constant 4 : index
    %c2 = constant 2 : index
    %c5 = constant 5 : index
    %c3 = constant 3 : index
    %0 = tensor.extract %arg1[] : tensor<f32>
    %1 = linalg.pad_tensor %arg0 low[%c4, %c5] high[%c2, %c3]  {
    ^bb0(%arg2: index, %arg3: index):  // no predecessors
      linalg.yield %0 : f32
    } : tensor<12x4xf32> to tensor<18x12xf32>
    return %1 : tensor<18x12xf32>
  }
```

However, we do not have `linalg.concat`, so the workaround is to use `linalg.init_tensor` and `linalg.fill` to create a placeholder.

```mlir
  func @concatenate(%arg0: tensor<2x2xi32>, %arg1: tensor<2x3xi32>) -> tensor<2x5xf32> {
    %c0_i32 = constant 0 : i32
    %2 = linalg.init_tensor [2, 5] : tensor<2x5xi32>
    %3 = linalg.fill(%2, %c0_i32) : tensor<2x5xi32>, i32 -> tensor<2x5xi32>  // This is just created for the dest of the first subtensor_insert
    %4 = subtensor_insert %0 into %3[0, 0] [2, 2] [1, 1] : tensor<2x2xi32> into tensor<2x5xi32>
    %5 = subtensor_insert %1 into %4[0, 2] [2, 3] [1, 1] : tensor<2x3xi32> into tensor<2x5xi32>
    return %5 : tensor<2x5xf32>
  }
```

I'm not really sure how would it gets lowered within linalg on tensor path. I'm afraid that we will still have something like

```
linalg.fill(%res, ...)    // This is redundant.  It was created for the dest of subtensor_insert
flow.tensor.update(%res, ...)
flow.tensor.update(%res, ...)
```

The problem is more like how do we allocate the buffer for the result of concatenate, and how to plug it into Linalg on tensors path. I feel this will be easier if we have `linalg.concat` or `flow.tensor.concat`.

For now, I'm using `linalg.fill` to put a placeholder, expect the pipeline create the buffer for it, and I'm afraid that the `linalg.fill` op will not go away so we will have an unneeded fill. We can see if this is an issue once we get concatenate op running end-to-end in the new path.

**Comment by MaheshRavishankar** [comment]
Right. This might be a case for `flow.tensor.concat`
