### ISSUE TITLE
Registry driver info enumeration should be const

### ISSUE THREAD

**Issue by ewconnell** [google/iree#5019]
When calling `iree_hal_driver_registry_enumerate` the pointers in the result list `out_driver_infos` should be `const`. I'm not sure if I've got it right, but I think it's
```
IREE_API_EXPORT iree_status_t IREE_API_CALL iree_hal_driver_registry_enumerate(
    iree_hal_driver_registry_t* registry, iree_allocator_t allocator,
    iree_hal_driver_info_t const ** out_driver_infos,
    iree_host_size_t* out_driver_info_count);
```
I tried to make the change, but it has a ripple effect through the api so best considered by someone who knows the full impact of such a change.

**Comment by benvanik** [comment]
Why should they be const? The memory is allocated and then ownership is transferred to the caller - who can do whatever they want with it - and then needs to free it. Note the comment:
```
// The provided |allocator| will be used to allocate the returned list and after
// the caller is done with it |out_driver_infos| must be freed with that same
// allocator by the caller.
```

**Comment by benvanik** [comment]
(this behavior is needed as the registry may be process-scoped and enumeration is a thread-safe query of the registry at a specific point in time - other threads may come in and change the registry internals after enumeration completes and if it had returned references to that memory then things go boom)

**Comment by ewconnell** [comment]
I see. I interpreted what was happening to be an allocated list of pointers to const driver info that was likely defined as static tables in the driver implementations so that no copying would be required. 
If we get a copy of the info and modify it, is there anything useful we can do with it? I assumed the primary purpose was reflection for selection.

**Comment by benvanik** [comment]
Yep there are no (user-visible) static tables in the drivers which is why this is required :)
The list of drivers and list of available devices per driver can change at any time. The only way to provide reflection over an ever-changing list of things is to either expose the locks to user code or make copies (or do some more entirely too complex for the task copy-on-write trickery). The information being copied here is small and transient (can come from arenas/etc) and much harder to mess up than trying to properly juggle the driver/device locks involved - same rules as things like strdup: just free the memory you get back.

Whether there's value in one messing with the contents of the pointers is up to the caller - I wouldn't, but you need a non-const pointer to free and as such there's no value in making it const: you'd have to cast away the constness to free it at which point the semantic meaning of const pointers becomes meaningless. It's the same reason why strdup returns char* instead of const char* - what the owner of the memory does with it once they get it is up to them. I'd never try to free a const char*, so making something that needed to be freed const would be bad.

**Comment by ewconnell** [comment]
Yep makes sense! Thanks
