### ISSUE TITLE
unidirectional_lstm.mlir doesn't work with -iree-flow-dispatch-linalg-on-tensors

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5151]
**Describe the bug**
This test failed in DispatchLinalgOnTensorsPass. The error log can be found at https://gist.github.com/hanhanW/89a177694616a43a35da7abd11152d51

Short log:

```
error: operand #0 does not dominate this use
```

This failed in dispatch function creation stage, so it does not work on both CPU and GPU.

**To Reproduce**

Run: `iree-run-mlir iree/test/e2e/models/unidirectional_lstm.mlir -iree-hal-target-backends=vulkan-spirv -function-input="1x5xf32=[0,1,0,3,4]" -iree-flow-dispatch-linalg-on-tensors -iree-codegen-spirv-experimental-linalg-on-tensors -function-input="1x5x2x2xf32=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]"`

**Comment by hanhanW** [comment]
@MaheshRavishankar I'm not sure who is the best person for this bug, feel free to reassign to others.

**Comment by hanhanW** [comment]
One thing might help here, I hit an issue in this file when developing benchmarking tools. The main difference is that this file contains multiple blocks because it has a control-flow op (ie, mhlo.while op).

**Comment by MaheshRavishankar** [comment]
Ill take this one. It seems that this might help here https://reviews.llvm.org/D97887

**Comment by hanhanW** [comment]
I've seen the same issue happens in other integration model tests, fyi.

**Comment by MaheshRavishankar** [comment]
This patch to upstream fixes this particular issue https://reviews.llvm.org/D99226.

But it actually raises a slightly involved issue. The core issue is caused due to this method https://github.com/google/iree/blob/881de81238971869d6d62cabf8dc0b54a17be704/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp#L328. 
It is trying to bring in operations that can be fused with the ops in the dispatch region. This is hard to get correct when you have a DAG of operations to pull in. Instead
1) Try to canonicalize `subtensor`, `tensor_reshape`, etc and pull them into the dispatch region.
2) Use the `Flow::DispatchWorkgroupsOp` canonicalization to pull in operations like `init_tensor`, `constant` etc.

This will require some more work cause oeprations that dont fall into this category need to be pulled in this way are lowered to `flow.tensor.` operations. Some of that needs to be plumbed through as well #5105 . Going to keep the ticket on this one and see if I can drop the method linked above.

**Comment by hanhanW** [comment]
Can we close the issue in a change/PR that enables the test: https://github.com/google/iree/blob/main/iree/test/e2e/models/unidirectional_lstm.mlir

Or you think it is too fragile at this moment, people would be struggle on it?

**Comment by hanhanW** [comment]
Oh, I saw it in #5259

**Comment by MaheshRavishankar** [comment]
I'll close with it. It might not actually work though. I was getting an error on buffer allocation with that change. It went away on rebase, but I see there is a swift shader failure on CI. Need to investigate.
