### ISSUE TITLE
Move Jax (and all TF integrations) out of bindings/python

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#5181]
TF integrations have leaked out of `integrations/tensorflow`. The JAX tests rely on iree-import-xla. Let's keep these things separate. Stella says this is now possible because whatever weird Python thingy was preventing this before is no longer there (probably because we got rid of Bazel support).

**Comment by stellaraccident** [comment]
It is by design that the pure python frontend components for all frontends are in the main bindings tree (the ability to use the different frontends to compile is part of the public API -- actually having those frontends is not). To actually use them, you have to install a separate dep (and will be notified of such if you don't have it). We can separate the tests, though.

**Comment by ScottTodd** [comment]
Anything still left to do here? Looks like https://github.com/google/iree/tree/main/bindings/python has no tensorflow or jax code now.
