### ISSUE TITLE
GPU VectorizeMemRefPass does not work with inlined constants

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5330]
Coming from #5282, it broke MobileNetV2 on GPU in Linalg on tensors path.

From @antiagainst 
> The reason is constant inlining. We can inline several large constants in the same kernel right now. After bufferization we'll have memref.buffer_cast for them. Those memref.buffer_cast ops aren't recognized by VectorizeMemRefPass, which expects hal.interface.binding.subspan ops and turns vector.transfer_read into normal load ops.

> We need to vectorize constants but `DenseElementsAttr` does not support vector element types.

The current workaround is to add `-iree-flow-inline-constants-max-byte-length=16`.

**Comment by MaheshRavishankar** [comment]
We should just drop the `VectorizeMemRefLoadStorePass`. It is not the way things need to be handled on the linalg on tensors path. The goal is to vectorize using Linalg -> Vector conversions. AFAIK this already happens in most cases (there might be a few missing cases). So this bug might not be relevant anymore.

@antiagainst @ThomasRaoux close this?

**Comment by ThomasRaoux** [comment]
@MaheshRavishankar I think there is a confusion with the old vectorization of elementwise ops Hanhan had implemented.  VectorizeMemRefLoadStorePass does the conversion of memref to memref of vector which is need because SPIRV doesn’t support casting of pointers. This is needed in addition to linalg vectorization. I don’t think we have an alternative at this point. 
That being said I implemented a fall back in case the memref vectorization fail and the transfer ops are now lowered to scalar load/store in this case so there shouldn’t be functional problem due to that but this will still generate sub optimal code. 

We might want to keep this issue open and address the code quality problem. What do you think?

**Comment by MaheshRavishankar** [comment]
Thanks for the clarification. Indeed I was confused by the other pass Hanhan had added (they have very similar names). But I remember now, there is actually no way of getting around the SPIR-V issue. I dont think this bug is needed. Its really not an issue that has an immediate fix or some real AI that we have to address it. It pretty much feels like a restriction we need to work with. So I'll close this bug.

**Comment by ThomasRaoux** [comment]
Sounds good. Should we open a new issue to keep track that we would fail vectorization of load/store? We might rediscover it later when profiling but since this is a known issue it is probably better to keep some log of it to know and address it in the near future. I can file it and assign it to myself if it needs a owner.
@MaheshRavishankar what do you think?

**Comment by MaheshRavishankar** [comment]
I think something more specific would be useful. General shortcomings of the lowering are hard to document. If we have a specific example where things don't work or a specific code pattern we would like to document, that makes sense to track with an issue. I am trying to reduce noise in our issue tracking by closing issues that aren't specific enough or don't have a description of what the final state should be.

**Comment by ThomasRaoux** [comment]
Got it, I'll get the IR for the MobileNet case and file an issue specific to that.
