### ISSUE TITLE
Control over executing each dispatch region on a CPU thread 

### ISSUE THREAD

**Issue by nick-furry** [google/iree#5437]
I'm trying to understand how IREE executes each dispatch region on a x86 system. Does each dispatch region execution occur on different threads implicitly or is it upon the user to specify multi-threaded execution? In either case how can I specify the thread that each region should run on?

Thank you.

**Comment by benvanik** [comment]
Dispatch regions are distributed across a set of threads in a thread pool. How the thread pool is configured is controllable (how many threads, what the affinity of those threads is) as are the distribution characteristics of each dispatch (the workgroup count - basically, how many subtasks each dispatch will be broken into), but there's intentionally no fine-grained control over which thread a particular subtask of dispatch runs on.

It's helpful to understand what you're trying to do/what angle you're coming at the question from - it's a big space :)

**Comment by nick-furry** [comment]
I'm trying to target IREE for distributed applications and as a first step I wanted to see how I can distribute amongst threads in  a single node. Is there an example of how to configure the thread pool and dispatch?

**Comment by benvanik** [comment]
Today there is the flag `--dylib_worker_count=` that sets the thread count (0 will auto-select up to `--dylib_max_worker_count=`). The heuristics used for things aren't tuned at all and really need to be reworked. The best thing to do to experiment would be to change this code:
https://github.com/google/iree/blob/6ef847398348eb967063f019de73fb6d0e40f9eb/iree/hal/dylib/registration/driver_module.cc#L66-L75

The entire dylib driver_module.c file linked above is optional and you can do exactly what it is in your own application (define the topology, create the iree_task_executor_t, and then create the HAL driver) - #4298 is tracking removing it so that applications have more control with less code duplication, but TBD.

That's using helpers from here, but you can change it to do whatever you want:
https://github.com/google/iree/blob/6de6fdf6186dec8226d751ec4c491c459bd97bc9/iree/task/topology.h#L124-L170

You are basically just defining thread groups, setting their affinity (which cores the group is assigned to), and optionally indicating which threads you want to prioritize intra-thread workstealing (indicated by constructive_sharing_mask).

The intent is to make that all configurable with a flag but that's still TODO:
https://github.com/google/iree/blob/76808e69d9c7f2fd06b7b1c6207b5d215df1e8f4/iree/task/topology.c#L47-L51

There's lots of room for improvement (consider what's there as a v0) - any feedback/contributions are appreciated :)
If you want to get a feel for how the threading is working you can use tracy; the task system is fully instrumented:
![image](https://user-images.githubusercontent.com/75337/114800639-edf1f880-9d4e-11eb-9fb3-61449ab0c685.png)

**Comment by benvanik** [comment]
oh there are some notes there about donated threads - that's still TODO but that's another approach if you are interleaving IREE work with other scheduling systems - you'd use the topology to declare what IREE should try to schedule on, then donate threads using iree_task_executor_donate_caller to process the work whenever and wherever you wanted:
https://github.com/google/iree/blob/6ebb663bb27cd9d40c57a7898780fc6749249e3e/iree/task/executor.h#L354-L383

(that entire executor.h has a lot of details of the system, if you're interested :)

**Comment by nick-furry** [comment]
Thank you for the details Ben  :)

**Comment by benvanik** [comment]
(closing for now - feel free to hop on discord or ask more questions in the future :)

**Comment by benvanik** [comment]
A dispatch region is simply a parallel-for - each invocation of the body of the region (like the body of a for loop) is a workgroup. So a dispatch over 1,1,1 (1 total workgroup) runs a single workgroup, while a dispatch over 128,128,2 runs 32768 workgroups. Each workgroup - like the body of a parallel-for - can overlap in execution.

This means that workgroups of the same dispatch region can always run in parallel. Workgroups of different dispatch regions may or may not run in parallel depending on whether there is a data dependency.

In this example:
```mlir
%0 = flow.dispatch @ex::@dispatch0[%c4, %c1, %c1](%arg0) : (tensor<4xf32>) -> tensor<4xf32>
%1 = flow.dispatch @ex::@dispatch1[%c8, %c2, %c1](%0) : (tensor<4xf32>) -> tensor<4xf32>
%2 = flow.dispatch @ex::@dispatch2[%c4, %c2, %c1](%0) : (tensor<4xf32>) -> tensor<4xf32>
```
dispatch0 can run its 4 workgroups in parallel (4,1,1), and after all of those workgroups complete and %0 is available then both dispatch1 and dispatch2 that consume %0 can run their 16 (8,2,1) and 8 (4,2,1) concurrently.

This manifests lower in the stack (and closer to the runtime) as `hal.command_buffer.dispatch` and `hal.command_buffer.execution_barrier` ops:
![image](https://user-images.githubusercontent.com/75337/117870808-74680000-b251-11eb-956e-57edf7538fcc.png)

**Comment by benvanik** [comment]
At the flow dialect level they are the unscaled XYZ workgroup ranges - in a classic parallel-for you can think of it as the range (from 0,0,0 -> X,Y,Z). When lowering into the hal dialect the size of each workgroup is computed and that is applied (`workgroup_count = workgroup_range / workgroup_size`).

So picking some larger sizes for an example, a flow.dispatch with `[1024, 512, 1]` will get lowered into a hal.command_buffer.dispatch as `[1024/workgroup_size_x, 512/workgroup_size_y, 1/workgroup_size_z]`. How the workgroup sizes are calculated is up to each backend - a GPU would have very different sizes than a CPU, for example, but they are still working with the same range of data. The entire relationship between the workgroup XYZ and the actual data processed is entirely controlled by a simple function `f(x,y,z)` - this function could, for example, just do `f(x,y,z) = (x*y*z, 1, 1)` to flatten out the range, etc.

The actual conversion doesn't exist yet (because no one is producing scf.parallels), but you can think of [`scf.parallel`](https://mlir.llvm.org/docs/Dialects/SCFDialect/#scfparallel-mlirscfparallelop) being something that can lower into a `flow.dispatch.workgroups`. The workgroup count is the range from lower->upper and the workgroup size is the step. The grid dispatch model used by the dispatch regions is just 3 of those scf.parallel loops nested within each other.

The implementation is as straightforward as you can imagine:
```c++
for (int workgroup_z = 0; workgroup_z < workgroup_count_z; ++workgroup_z) {
  for (int workgroup_y = 0; workgroup_y < workgroup_count_y; ++workgroup_y) {
    for (int workgroup_x = 0; workgroup_x < workgroup_count_x; ++workgroup_x) {
      int workgroup_index =
          workgroup_z * workgroup_size_x * workgroup_size_y * workgroup_size_z +
          workgroup_y * workgroup_size_x * workgroup_size_y +
          workgroup_x * workgroup_size_x;
      // and other fancy indexing math
    }
  }
}
```

(this is how GPUs and GPU APIs (CUDA/OpenCL/Vulkan/Metal/etc) handle work distribution - nothing IREE-specific here, just that we map to it nicely :)

**Comment by nick-furry** [comment]
Thank you Ben, these definitely clarified my understanding of workgroup and dispatch regions. What I'm trying to do for my use case is I'm trying to create one executable binary per dispatch region and execute that binary over multiple threads where workgroups could run in parallel if possible. 

The pass flow that I'm thinking is as follows:
MHLO MLIR -> HLO to linalg -> linalg to llvm codegen -> extract dispatch regions -> translate to vm bytecode -> execute

I'm taking `iree/test/e2e/models/edge_detection.mlir` as the example IR. I converted MHLO to linalg along with other flags as follows:
```
./build/iree/tools/iree-opt -iree-flow-hlo-to-hlo-preprocessing -iree-flow-extract-pad-from-conv  --iree-codegen-hlo-to-linalg-on-tensors --iree-flow-dispatchability-analysis --iree-flow-identify-dispatch-regions2 --iree-codegen-llvm-generic-ops-workgroup-size=4 ./iree/test/e2e/models/fullyconnected.mlir
```

The output IR has `linalg.generic` but I do not see any mention of workgroup in it. Could you throw your thoughts on this approach that I've taken? Thanks!

**Comment by nick-furry** [comment]
I've been able to make some progress towards getting a bytecode. The flow was `MHLO -> linalg -> linalg with dispatch -> HAL code`.
```
>> ./iree-opt --iree-codegen-hlo-to-linalg-on-tensors file.mlir | ./iree-opt -iree-flow-dispatch-linalg-on-tensors-pass -canonicalize -cse | ./iree-opt -iree-hal-target-backends=dylib-llvm-aot -iree-flow-outline-dispatch-regions2 -iree-hal-materialize-interfaces2
```

Not sure if the way of generating HAL code is right since there's another relevant pass - `iree-convert-to-hal`. Also, this HAL code still contains flow dispatch dialect, not sure if that can be directly lowered to vm code and bytecode thereafter.

Tried `iree-convert-hal-to-vm` to generate vm code with varying successes. Say for example the mlir in test that I linked above converted successfully but other examples that I've been trying on (matmul and conv) has been failing so far with different errors with this approach. For example, I get `error: 'flow.dispatch' op operand #0 must be index, but got 'i32'` when trying to lower a conv mlir #5949
