### ISSUE TITLE
Snapshot releases failing with unknown target for `iree-translate`

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#5615]
```
2021-04-26T10:12:32.8870660Z CMake Error at build_tools/cmake/iree_bytecode_module.cmake:74 (add_custom_command):
2021-04-26T10:12:32.8872959Z   Error evaluating generator expression:
2021-04-26T10:12:32.8874224Z 
2021-04-26T10:12:32.8876342Z     $<TARGET_FILE:iree-translate>
2021-04-26T10:12:32.8877292Z 
2021-04-26T10:12:32.8878648Z   No target "iree-translate"
2021-04-26T10:12:32.8879956Z Call Stack (most recent call first):
2021-04-26T10:12:32.8883398Z   iree/samples/simple_embedding/CMakeLists.txt:47 (iree_bytecode_module)
```

This one is affecting the runtime build, which seems as though it now has an implicit dependency on the compiler.

**Comment by ScottTodd** [comment]
The whack-a-mole setting exclusions in https://github.com/google/iree/blob/main/iree/samples/simple_embedding/CMakeLists.txt continues :P

**Comment by ScottTodd** [comment]
(fyi @hcindyl )

**Comment by hcindyl** [comment]
Yes there's a dependency in `iree_bytecode_module` of `iree-translate`. (https://github.com/google/iree/blob/main/iree/tools/compilation.bzl#L20) It didn't show problems before because the code path `iree/samples/` was guarded behind the `IREE_BUILD_SAMPLES` flag, but now it is accessible with `IREE_BUILD_EMBEDDING_SAMPLEs` flag (https://github.com/google/iree/blob/main/CMakeLists.txt#L476)

We can change the flag to be off by default so the cmake behavior can be the same as before. For users want to build `simple_embedding_run` in runtime they need to turn the flag on (and provide the `IREE_HOST_BINARY_ROOT` path to retrieve iree-tranlate binary)

**Comment by ScottTodd** [comment]
Flipping that flag off by default SGTM for now.

I'll want to establish some more principles for features required by samples and how samples are included in build configurations as part of https://github.com/google/iree/issues/5222.

**Comment by hcindyl** [comment]
Another approach is to generate the prebuilt bytecode module (similar to the one for the RISC-V config stored in `iree/samples/simple_embedding/data` so we can retire iree_byte_module in the sample code path. The concern is the prebuilt may not be compatible with ToT if there's any ABI/toolchain change.

**Comment by hcindyl** [comment]
https://github.com/google/iree/pull/5618 turns the flag off.

**Comment by stellaraccident** [comment]
thanks all - I agree with Scott about some more principled separation between building the core system and samples (but don't have anything more concrete to add off the top of my head)
