### ISSUE TITLE
Add tests using executables to the HAL CTS

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#5678]
- [ ] `executable_cache` (started [here](https://github.com/ScottTodd/iree/commit/b91348ea9b46a71b851b875509f1ece8f8d56a5b)): preparing executables
- [ ] `iree_hal_command_buffer_dispatch`: running executable code

These mostly need a way to generate executable data compatible with each HAL driver (for which https://github.com/google/iree/issues/4643 will be helpful), then a way to load that data into tests (`iree_c_embed_data`?)

Once we have basic coverage of `iree_hal_command_buffer_dispatch`, we can start building more complex test coverage for things like push constants, descriptor sets, workgroup indices, etc. - getting closer to having the CTS answer "is this implementation correct" vs "does this implement the API at all".

**Comment by ScottTodd** [comment]
Now that https://github.com/google/iree/issues/4643 is resolved, this is definitely easier.

We still need a convenient way to get produce backend-specific hal.executables, but once we have that we can have each `iree/hal/*/cts/CMakeLists.txt` include the generation code and then pass that output as a dep to any `iree/hal/cts/*_test.h` files. Depending on how uniform the generation code is, we could even fold it into the CMake `iree_hal_cts_test_suite` function.

An iree-translate mode for IR -> hal.executable that serializes the hal.executable variant you provide should do the trick, then we can use iree_bytecode_module to get a c_embed_data dep with the binary contents of the serialized executable without any new CMake code.

**Comment by benvanik** [comment]
on it!

I'll be adding an iree-translate mode of `iree-mlir-to-hal-executable` - that'll spit out a binary in the native format of whatever backend is chosen (elf, flatbuffer containing spirv, etc) and we can embed_data it. Probably worth wrapping in an `iree_hal_executable` cmake rule or something that does the right iree-translate invocation - it could use iree_bytecode_module internally if that made sense, but since it's not a bytecode module I wouldn't want to expose that - future me would get very confused :P
