### ISSUE TITLE
Segmentation fault when benchmarking MobileNet with 3 threads on Android

### ISSUE THREAD

**Issue by antiagainst** [google/iree#5857]
**Describe the bug**
Segmentation fault when benchmarking MobileNet with 3 threads on Android

**To Reproduce**
* Download artifacts from https://buildkite.com/iree/iree-android-benchmark/builds/2475#e8dcc558-0fd2-466d-93ad-2d509c941b77
* Push artifacts to `/data/local/tmp/benchmark_tmpdir`.
* Run on an Android phone: 

```
adb shell LD_LIBRARY_PATH=/data/local/tmp \
taskset f0 /data/local/tmp/benchmark_tmpdir/iree-benchmark-module \
--flagfile=/data/local/tmp/benchmark_tmpdir/mobilenet-v2_flagfile \
--module_file=/data/local/tmp/benchmark_tmpdir/mobilenet-v2_Pixel4_cpu3t.vmfb \
--driver=dylib --benchmark_repetitions=10 --task_topology_group_count=3
```

**Comment by antiagainst** [comment]
Assigning to @asaadaldien as this starts from https://github.com/google/iree/commit/871d203660818dff00d252c1351d4b3eee6bafd8.

**Comment by asaadaldien** [comment]
[871d203](https://github.com/google/iree/commit/871d203660818dff00d252c1351d4b3eee6bafd8) promotes subviews to full tile buffers allocated on the stack, with more threads running at the same time this may exceed the process stack-limit and cause a stackoverflow segfault. We can increase the stack limit if we are running on a rooted device

This is why I want to avoid using `alloca` in the LLVM side and have an IREE cached allocator instead to use for within dispatch region scratch memroy allocations cc: @benvanik

**Comment by benvanik** [comment]
how much stack are you using? we can specify our own thread stack sizes when we create them, so long as what you're using is reasonable (<=64KB).

**Comment by antiagainst** [comment]
Thanks for the explanation, Ahmed! IMO, increasing the stack limit is not be the prefered way. This is different from pinning down to a thread, where we use for benchmarking stability. It does not impact the general applicability there.

 Looks it will take some time to address this issue. In the meanwhile, I think we should revert the change for this specific benchmark or disable this specific benchmark?

**Comment by benvanik** [comment]
Having a fixed available stack size on the worker threads is useful regardless and it simulates what workgroup shared memory does on GPUs. Right now we are defaulting to the platform stack size which varies (16KB, 1MB, etc) and that'll just cause problems.

I do have plumbing in place for passing in stack memory allocated external to the program (so that we can better bounds check it), but that needs some more work on the runtime side and work on the compiler side to properly manage the allocas. Today AFAIK the bufferization does not alias allocas meaning that if you alloca inside of a loop or multiple times you'll end up with something that either doesn't work or allocates way too much.

**Comment by asaadaldien** [comment]
> Thanks for the explanation, Ahmed! IMO, increasing the stack limit is not be the prefered way. This is different from pinning down to a thread, where we use for benchmarking stability. It does not impact the general applicability there.
> 
> Looks it will take some time to address this issue. In the meanwhile, I think we should revert the change for this specific benchmark or disable this specific benchmark?

Lets revert the change the promotion wont be needed after landing padding #5840.

**Comment by antiagainst** [comment]
> Having a fixed available stack size on the worker threads is useful regardless and it simulates what workgroup shared memory does on GPUs. Right now we are defaulting to the platform stack size which varies (16KB, 1MB, etc) and that'll just cause problems.

I see. Makes sense. My previous comment was on changing process default stack size using rooted phones.


> Lets revert the change the promotion wont be needed after landing padding #5840.

+1

**Comment by asaadaldien** [comment]
> Having a fixed available stack size on the worker threads is useful regardless and it simulates what workgroup shared memory does on GPUs. Right now we are defaulting to the platform stack size which varies (16KB, 1MB, etc) and that'll just cause problems.
> 
> I do have plumbing in place for passing in stack memory allocated external to the program (so that we can better bounds check it), but that needs some more work on the runtime side and work on the compiler side to properly manage the allocas. Today AFAIK the bufferization does not alias allocas meaning that if you alloca inside of a loop or multiple times you'll end up with something that either doesn't work or allocates way too much.

Correct! the good news is all alloca's in the code we generate are are hoisted nothing in the ineer most loop.

**Comment by asaadaldien** [comment]
Yeah the hypothesis were correct, the multi-threading will work by increasing the per-thread stack size
I just doubled the [default]( https://github.com/google/iree/blob/main/iree/base/internal/threading_pthreads.c#L155) 
 ```c++
  size_t stack_size;
  pthread_attr_getstacksize(&thread_attr, &stack_size);
  pthread_attr_setstacksize(&thread_attr, stack_size * 2);
 ```
 and I can run the multitheading version.
 
As short term solution we can slightly  increase the size  or do something like `stack_size = ulimit -s / num_workers`.
Also we can have a runtime flag to set `iree_thread_create_params_t::stack_size`

@benvanik thoughts ?

**Comment by benvanik** [comment]
I think we can pick a reasonable size like 32 or 64KB and then ensure the compiler also observes that limit. 32 or 64KB per thread seems totally reasonable. We can then expose that to the runtime via a device query, but really being able to fix a size makes things so much nicer.

**Comment by benvanik** [comment]
This is the equivalent vulkan value: https://vulkan.gpuinfo.org/displaydevicelimit.php?name=maxComputeSharedMemorySize&platform=windows

**Comment by asaadaldien** [comment]
I think we are > 64KB, I am getting a trace to look at the stack usage.

**Comment by benvanik** [comment]
yeah we don't want transient tile allocations to be that big regardless of stack limits - 32 or 64KB at most :)

**Comment by asaadaldien** [comment]
Trace didn't help tracking the stack sizes (very likely not sampling stack usage or I am not looking at the right thing :p) 
But for that particular model there is a matmul where each tile allocates 221 KB. 
See padding pass debug logs:

```
Problem-size: [49,1024], [1024,1024]
Workgroup-tile-sizes:[64, 64]
L1-tile-sizes:[32, 32,32]
Vector-tile-sizes:[4, 4, 4]
LHS after padding:[52,1024], size_in_bytes = 212992 (allocation: stack)
RHS after padding:[1024,64], size_in_bytes = 262144 (allocation: reused)
Result after padding:[52,64], size_in_bytes = 13312 (allocation: stack)
```

In the compiler side: To bound the required stack for padding we can try to push the padding a level down and pad each L1 tile but that will come at the cost of more copies in the inner loop. Also we can't do that now before getting `linlg.tiled_loop` in order to move any tiling on tensors to be supported by bufferization.

In the runtime side: I queried the default `stack_size` and its ~1M which means there is a single thread context switching between multiple tiles (I can't read that in Tracy very well) ?

In any case, IMO the mid-term solution is to increase the stack_size or control it with a runtime flag till we get more compiler/runtime support.

**Comment by benvanik** [comment]
The stack size of one thread does not impact the stack size of any other thread: each thread has its own stack, and the number of threads does not diminish any shared resource beyond physical memory for wired pages (but there are GB of those). You can have per-thread stack sizes of 1GB if you wanted - it's just a virtual address space reservation. If reducing the number of threads makes the issue go away that just means that program behavior is changing enough to not trigger the issue. If this were a memory stomping issue it would go away if memory was rearranged such that stomped memory was not used for something critical, for example. Changing the number of threads to make the problem go away is like adding random sleep() calls until a program doesn't crash: it's just changing behavior until an issue does not trigger _in one particular case_.

Context switching has no relation to this: we have N threads, where each thread is just calling into the generated code in a loop. There's no overlapping execution or mid-tile switching: it's literally a for loop around a function call. The stack size as it relates per thread is limiting the total size of any single stack frame of a single workgroup invocation with no relation at all to cross-workgroup execution.

200KB+ is a lot for the stack. It'd be worth doing some profiling on this to make sure that's having the intended benefit (I suspect it is, but caches are magical beasts and we have major work distribution issues to fix before that's our primary issue). It may be fine on one device but we'd want to ensure that all fits in L2 (if it exists) - otherwise it's just loading from main memory (or contended L3, if it exists) to then spill back to main memory. Whatever amount is chosen needs to be something we can specify in the compiler with a maximum (whether that max is specified during compilation or queried at runtime), and is the purpose of the workgroup size: a device with no L2 cache or a very small amount of memory absolutely cannot have these extra intermediate allocations. Some of the devices we are going to run on barely have 256KB of total memory!

**Comment by asaadaldien** [comment]
> The stack size of one thread does not impact the stack size of any other thread: each thread has its own stack, and the number of threads does not diminish any shared resource beyond physical memory for wired pages (but there are GB of those). You can have per-thread stack sizes of 1GB if you wanted - it's just a virtual address space reservation. If reducing the number of threads makes the issue go away that just means that program behavior is changing enough to not trigger the issue. If this were a memory stomping issue it would go away if memory was rearranged such that stomped memory was not used for something critical, for example. Changing the number of threads to make the problem go away is like adding random sleep() calls until a program doesn't crash: it's just changing behavior until an issue does not trigger _in one particular case_.
> 
> Context switching has no relation to this: we have N threads, where each thread is just calling into the generated code in a loop. There's no overlapping execution or mid-tile switching: it's literally a for loop around a function call. The stack size as it relates per thread is limiting the total size of any single stack frame of a single workgroup invocation with no relation at all to cross-workgroup execution.

Yes, thanks for detailed explanation that's also my understanding of user space threading on Unix. I don't know the full details of our task system you built it so you know the best :) . I am mainly trying to  explain my observation of the consistent behavior where running 3 threads requires 2x default thread stack size.

> 200KB+ is a lot for the stack. It'd be worth doing some profiling on this to make sure that's having the intended benefit (I suspect it is, but caches are magical beasts and we have major work distribution issues to fix before that's our primary issue). It may be fine on one device but we'd want to ensure that all fits in L2 (if it exists) - otherwise it's just loading from main memory (or contended L3, if it exists) to then spill back to main memory. Whatever amount is chosen needs to be something we can specify in the compiler with a maximum (whether that max is specified during compilation or queried at runtime), and is the purpose of the workgroup size: a device with no L2 cache or a very small amount of memory absolutely cannot have these extra intermediate allocations. Some of the devices we are going to run on barely have 256KB of total memory!

What we are doing here is padding  the entire workgroup tile (like other matmul layout packing systems e.g ruy), that happens once before starting any computation where we copy the tile into the padded layout. The thing that will affect the cache behavior is data traversal order and its spatial relation to the  SIMD instructions not the size of that packed layout. In facet since this is a copy of a slice of the original matrix the distance between consecutive rows is smaller which will have better locality and less chances of aliasing). 
IMO 200KB+ is reasonable for these kind of things (e.g packing an img2col buffer for implicit gemm) it doesn't have to be a stack we can have a cached allocator or as you mentioned before a pre allocated shared stack. Its done now on stack because its the only lightweight thing we can do within a dispatch region.

Here are traces I captured yesterday with padding (1 thread vs 3 threads with double the stack size)
[mobilenet_v2_traces.tar.gz](https://github.com/google/iree/files/6475756/mobilenet_v2_traces.tar.gz)

**Comment by MaheshRavishankar** [comment]
Should be superceded by #6973 . Closing
