### ISSUE TITLE
Unsupported mhlo.dot_general form

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#6105]
Hey mhlo/linalg gurus, I have a model that has the following in it:

```
%234 = "mhlo.dot_general"(%216, %233) {dot_dimension_numbers = {lhs_batching_dimensions = dense<[0, 2]> : tensor<2xi64>, lhs_contracting_dimensions = dense<3> : tensor<1xi64>, rhs_batching_dimensions = dense<[0, 2]> : tensor<2xi64>, rhs_contracting_dimensions = dense<3> : tensor<1xi64>}, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<1x1x8x64xf32>, tensor<1x512x8x64xf32>) -> tensor<1x8x1x512xf32>
```

And it is failing to lower to linalg. Does anyone who has stared at these things before see the issue?

**Comment by hanhanW** [comment]
I think this would be canonicalized to a 3-D `mhlo.dot_general` in HLOToHLOPreprocessing pass, and then we will lower it to a `linalg.batch_matmul` op in HLOToLinalgOnTensors pass. Let me take a look at it after lunch.

**Comment by hanhanW** [comment]
The reason is that the batch dims are not consecutive. We can't handle it because we expect the reshape op is either collapsing or expanding.

https://github.com/google/iree/blob/64f9557e511f7d1ca7704789cb6a16c0aa414cf7/iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp#L610-L629

In the beginning, I found that this is an unit dim case. We can apply reshape in this case. After thinking a bit more, I think we can insert some transpose ops before and after dot_general, then we can apply RankReducedDotGeneral pattern and handle all the cases.

(putting a prettier IR below)

```mlir
func @foo(%arg0: tensor<1x1x8x64xf32>, %arg1: tensor<1x512x8x64xf32>) -> tensor<1x8x1x512xf32> {
  %0 = "mhlo.dot_general"(%arg0, %arg1) {
    dot_dimension_numbers = {
      lhs_batching_dimensions = dense<[0, 2]> : tensor<2xi64>,
      lhs_contracting_dimensions = dense<3> : tensor<1xi64>,
      rhs_batching_dimensions = dense<[0, 2]> : tensor<2xi64>,
      rhs_contracting_dimensions = dense<3> : tensor<1xi64>
    },
    precision_config = ["DEFAULT", "DEFAULT"]
  } : (tensor<1x1x8x64xf32>, tensor<1x512x8x64xf32>) -> tensor<1x8x1x512xf32>
  return %0 : tensor<1x8x1x512xf32>
}
```
