### ISSUE TITLE
`enable_benchmark` flag to IREE compiler API is unreliable

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#6196]
The pass that this relies on needs to be relayered in order to be robust. Disabling the exercise of this option in the one e2e test which invokes it.

Reproducer: `-iree-mhlo-input-transformation-pipeline -iree-flow-transformation-pipeline -iree-flow-export-benchmark-funcs`
```mlir
func @simple_mul(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub, iree.module.export} {
  %0 = hal.tensor.cast %arg0 : !hal.buffer_view -> tensor<4xf32>
  %1 = hal.tensor.cast %arg1 : !hal.buffer_view -> tensor<4xf32>
  %2 = mhlo.multiply %0, %1 {name = "mul.1"} : tensor<4xf32>
  %3 = hal.tensor.cast %2 : tensor<4xf32> -> !hal.buffer_view
  return %3 : !hal.buffer_view
}
```

**Comment by benvanik** [comment]
The root issue is that the benchmark functions need to be `() -> ()` and that means when taking a function with inputs we need to create dummy inputs matching the types and this doesn't work with custom types (`!hal.buffer_view` in this case, but any custom dialect type would have the same issue). It also doesn't work with dynamic shapes but that's an issue with the pass itself.

Instead of performing this deep within the flow dialect we should probably move this up to the head of the pipeline where we still have original types - though that still doesn't handle custom types (strings, tensorlist, etc). We could, when generating the ABI signature that turns tensor->buffer_view, add an argument attribute containing the original type that the pass could use - though that still may not capture the information we need (as there could be dynamic shapes).

All of this brittleness and limited applicability is making me lean towards not supporting this at all. There's nothing specific about creating dummy arguments, so shifting this responsibility to the frontends that have much better information/semantics seems like it would be better: how one generates valid no-input functions for savedmodel differs from tflite differs from numpy/etc.
