### ISSUE TITLE
Some deps are not added automatically after running bazel_to_cmake.py

### ISSUE THREAD

**Issue by hanhanW** [google/iree#6363]
I hit the issue when adding transforms to LinalgExt, and I found that others hit it before.

E.g.,

https://github.com/google/iree/blob/134edde9a9459fac4653fbfaca43b703ea054474/iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt#L82-L87

To repro:

1. Delete `add_dependencies`.
2. Run `python build_tools/bazel_to_cmake/bazel_to_cmake.py --dir iree/compiler/Dialect/Flow/Transforms`

**Comment by benvanik** [comment]
That just seems like someone didn't update the build file? The bazel rule doesn't depend on those targets so of course they won't get pulled in by bazel to cmake :P https://github.com/google/iree/blob/134edde9a9459fac4653fbfaca43b703ea054474/iree/compiler/Dialect/Flow/Transforms/BUILD#L65

**Comment by GMNGeoffrey** [comment]
The PassesIncGen dep is there

https://github.com/google/iree/blob/134edde9a9459fac4653fbfaca43b703ea054474/iree/compiler/Dialect/Flow/Transforms/BUILD#L64

The issue is this special carveout

https://github.com/google/iree/blob/0098f7de932fffc9c07ee820b90a01b28a0b98db/build_tools/bazel_to_cmake/bazel_to_cmake_converter.py#L129-L135

which is justified based on ALWAYSLINK, so we can maybe get rid of it, but I suspect the issue may have to do with what constitutes a "library" and the use of DEPENDS vs LINK_LIBS in CMake. I'll poke around

**Comment by hanhanW** [comment]
The main issue I hit was the tests were excluded without the deps, and I found this could address the issue. I'm not sure if they are related...

**Comment by GMNGeoffrey** [comment]
Not sure I understand what you're talking about with the tests, but https://github.com/google/iree/pull/6370 should fix this
