### ISSUE TITLE
What is the flagfile here

### ISSUE THREAD

**Issue by chiachia36** [google/iree#7256]
Hi,
I tried to run the instruction in this page [Getting Started on RISC-V with CMake](https://github.com/google/iree/blob/main/docs/developers/get_started/getting_started_riscv_cmake.md).
I am curious about what is the flagfile here? (at the end of the page)
![圖片](https://user-images.githubusercontent.com/40784675/135999892-97879181-ede0-49a1-879f-40bec3d7b72c.png)

Thanks!

**Comment by GMNGeoffrey** [comment]
FYI, the docs under docs/developers don't tend to be as polished as those on our website and are more likely to be outdated. A flagfile is a file that contains newline-separated flags which are processed exactly as if they were passed on the command line. We used to have a way to generate these from integration tests so you could get a valid set of inputs for a big model, but that functionality has gone away. For this specific case, I think you should be able to just specify flags as above, though perhaps the intent here was to have this be run on a larger model with more complex inputs, since it's looking at vectorization, specifically.

@hcindyl could you update these docs to reflect what arguments you might expect to be passed here?

In terms of generating inputs that can be used with command line tools from python-level models, there's now funcionality to generate yaml files with some brief documentation at https://github.com/google/iree/blob/main/bindings/python/iree/runtime/README.md. I haven't used it yet myself, so can't really elaborate further on how it works.

**Comment by GMNGeoffrey** [comment]
https://github.com/google/iree/issues/6688 is the issue for improving the documentation on the new tracing functionality
