### ISSUE TITLE
Benchmark multi-threaded on big cores

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#7804]
Even though we don't believe that being allocated multiple big cores for an extended period of time is a realistic scenario on current android phones, it would still be useful to run multi-threaded benchmarks on big cores. We haven't really optimized for little cores, which have a significantly different architecture (in order vs out of order execution) and so the multi-threaded benchmarks there aren't telling us as much as we'd like. The cost of adding these benchmarks is extra latency on the benchmarking pipeline, but big-core is much faster than little core and multi-threaded is even faster, so it shouldn't be a huge difference

**Comment by benvanik** [comment]
+1!

(just wanted to note that I most certainly don't believe that big cores can't be used for extended periods of time (see: games), and a large number of ML use cases are not about sustained non-stop execution and would be much happier to have 4+x lower latency for their bursty workloads :)

**Comment by GMNGeoffrey** [comment]
> (just wanted to note that I most certainly don't believe that big cores can't be used for extended periods of time (see: games), 

My understanding from @bjacob is that if you have 2 big cores running at full tilt you will start getting thermally throttled after less than a second

**Comment by bjacob** [comment]
Do you know that big cores are used while running games on an android phone?  (honest question - systrace'ing a game would tell. we can follow up internally to find out answers.).

**Comment by benvanik** [comment]
Always important to identify which experiential statements in one area carry over to frameworks and tooling that have a large variety of usage scenarios - doesn't mean the observations were wrong, only that the problem space is much different and larger here :)

Games generally run on big cores with the guidance being to run latency-insensitive background tasks on the little cores, e.g.
https://developer.android.com/games/optimize?hl=zh-cn#defer-work-to-slow-cpus
There's also fun things like this deep dive: https://www.androidauthority.com/fact-or-fiction-android-apps-only-use-one-cpu-core-610352/
![image](https://user-images.githubusercontent.com/75337/144518115-04e3e21e-2f91-49a7-a4cb-549abadc35a7.png)

Concretely a lot of ML workloads - especially mobile ones - don't even run longer than a second and _especially_ if on the big cores (200ms on big and then done is better than 4sec on little competing with other work, from a system health perspective). We also have very different threading characteristics than older frameworks that would do things like spin in-between work or only use single threads for a majority of the time: we look a lot more like a game engine than an ML framework.

Doesn't mean that certain models with certain use cases won't match the previous experience, only that they are a fractional part of the total set of scenarios we are targeting. As a framework our job is to let the user make the decisions for their particular scenario as we don't own their code or application and we cannot blindly make assumptions that dramatically impact a large chunk of those scenarios. Someone looking to use BERT to translate text in a chat application once every few minutes for 150ms each invocation should not suffer because we only tuned our framework to target a mobilevision model running at 90hz on 4k images for hours on end.

**Comment by benvanik** [comment]
(also interesting: https://developer.qualcomm.com/sites/default/files/docs/adreno-gpu/developer-guide/cpu/cpu.html#controlling-task-execution + https://developer.qualcomm.com/sites/default/files/docs/adreno-gpu/developer-guide/cpu/cpu.html#use-big-cores-for-compute-intensive-tasks)

**Comment by bjacob** [comment]
> Games generally run on big cores with the guidance being to run latency-insensitive background tasks on the little cores, e.g. https://developer.android.com/games/optimize?hl=zh-cn#defer-work-to-slow-cpus

Thanks for the very interesting link! I learned a few things there, including, not least, the existence of the NDK Thermal API --- going to be super handy.

Quick check though that I'm reading correctly the paragraph you linked to above. In my reading, it's not suggesting that we should or can get anything scheduled specifically on a big core. It's saying that games should use `sched_setaffinity` to explicitly tell non-latency-critical, short-duration tasks to go on little cores. Otherwise, such tasks might go on big cores, which would be wasteful.

Note that we know as a matter of fact that for normal android programs, `sched_setaffinity` (which again is the method pointed to by the above link) only works at best to pin to slow cores. The cpuset bits mapping to big cores are disregarded in my experience. There seems to be an exception when the calling process is `taskset` though -- `taskset` does work and I believe I strace'd it once and it did nothing else than calling `sched_setaffinity`. Not such how that works!

Anyway, my summary of the above link would be:
* Let the game main thread follow default scheduling (the article does not mention whether that would go on slow or fast cores in practice).
* Move as many auxiliary tasks as possible to worker threads and give them affinity to slow cores.

In other words --- still in my limited understanding!! --- the article doesn't say we can (or should) schedule anything on fast cores --- it says, on the contrary, that we can and should shedule *certain* things on slow cores.

> There's also fun things like this deep dive: https://www.androidauthority.com/fact-or-fiction-android-apps-only-use-one-cpu-core-610352/ ![image](https://user-images.githubusercontent.com/75337/144518115-04e3e21e-2f91-49a7-a4cb-549abadc35a7.png)

Thanks, that was an interesting article, and a blast from the past. Notice that the "quad core" SoC it refers to is a [Snapdragon 801](https://en.wikipedia.org/wiki/List_of_Qualcomm_Snapdragon_processors#Snapdragon_800,_801_and_805_(2013/14)) which has 4 symmetic out-of-order cores (Krait 400, similar to what we had in the Nexus 5).  And the "octa core" SoC it refers to is a [Snapdragon 615](https://en.wikipedia.org/wiki/List_of_Qualcomm_Snapdragon_processors#Snapdragon_610,_615_and_616_(2014/15)), which has 8 in-order Cortex-A53 cores --- branded a "4+4" asymmetric config but the only difference is in the clock speed, 1.5 GHz vs 1.0 GHz, so given that each of these cores has a fluctuating clock speed in practice, for our purposes it's essentially a symmetric platform.

That means that the "big" vs "LITTLE" distinction in the above graph is not very meaningul.

Another thing that I missed in the above article is was a mention of whether the benchmarks were run on battery or while charging.

> 
> Concretely a lot of ML workloads - especially mobile ones - don't even run longer than a second and _especially_ if on the big cores (200ms on big and then done is better than 4sec on little competing with other work, from a system health perspective). We also have very different threading characteristics than older frameworks that would do things like spin in-between work or only use single threads for a majority of the time: we look a lot more like a game engine than an ML framework.

Certainly, big cores are useful for short burst ML workloads.

**Comment by bjacob** [comment]
FWIW, none of that changes the fact that we all agree with @GMNGeoffrey 's rationale at the top of this issue. Let's have multi-thread big core benchmarks! No one's arguing against that.

**Comment by benvanik** [comment]
Yep! It's all about the scenario - if you are not latency sensitive then little cores are fine - if you are latency sensitive however they are not great. Lots of stuff factor into that as well - you may have multiple latency sensitive workloads - ML and otherwise - and want to allow ML to run on big core while forcing all your other stuff to run on the little cores if you know the ML workload is lighter. If your ML is synchronized to user input then you may never _choose_ to run on the little cores even if you can't force things to run on big cores - but that's where the OS scheduler comes in (they're never good, but a chance at getting something done several times faster is better than being guaranteed to be slower).

We need to be fast on both, and agreed that this is really about making sure we aren't blinding ourselves to one or the other (just as we shouldn't only run benchmarks on little cores we shouldn't only run on big ones).

It's just a snapshot, but mobilebert runs in 5.6s on 1 little core, 2s on 4 little cores, and 700ms on 1 big core - I'm excited to get the big core multithreading numbers as Vulkan on the same device runs in 190ms. I know almost nothing is tuned and our little core perf is not great yet, but the orders of magnitude are at least feeling ok 🎉

**Comment by GMNGeoffrey** [comment]
Accidentally marked the PR fixing (#7807) this as fixing itself :facepalm:
