### ISSUE TITLE
Converting a TF model to MHLO by the iree-import-tf

### ISSUE THREAD

**Issue by Jackwin** [google/iree#7960]
Hi Guys,

I just would like to convert a model from the TensorFlow, such as the [MobileNet V2](https://google.github.io/iree/ml-frameworks/tensorflow/#using-the-command-line-tool) in IREE example, to the MHLO dialect. In the tutorial, the Mobilenet V2  savemodel can be transformed to iree_input_mlir, which is Linalg. Could you provide which directive in iree-import-tf to make the conversion? Or give a command example?

Quite appreciate it. Thanks

**Comment by stellaraccident** [comment]
IREE's importers are built for getting into IREE, and their use of MHLO to get there from Tensorflow is an implementation detail. I believe there is a debugging flag that dumps the "mid level" representation, which is mostly MHLO. However, MHLO is not sufficient to represent Tensorflow programs and we do leverage other representations as needed.

I don't know why the Tensorflow team has never executed to make their stack more usable for these cases, but since these are implementation details of Tensorflow, if you need a better conversation story between tf and MHLO, they are the ones that need to do it in any kind of supported way. You are of course free to adapt our source code to your needs -- we just can't support it for more than it does in this front.
