### ISSUE TITLE
ConstEval depends unconditionaly on the VMVX driver

### ISSUE THREAD

**Issue by marbre** [google/iree#8196]
The target ConstEval runtime (`iree::compiler::ConstEval::Runtime`) unconditionally depends on the VMVX HAL driver:

https://github.com/google/iree/blob/0916baf04b08f5125ee6b9de65d0e9a11365a9b8/iree/compiler/ConstEval/CMakeLists.txt#L77

Trying to build IREE with

```
 -DIREE_HAL_DRIVER_DEFAULTS=OFF
 -DIREE_HAL_DRIVER_VMVX_SYNC=ON
```
hence fails (even though not the only error at the moment).

**Comment by benvanik** [comment]
We should always have the vmvx build rules be available (remove the if's from the build/cmake files).

**Comment by ScottTodd** [comment]
Yep, that dep is by design.

A few options

1. Make it conditional, so the compiler pass `-iree-consteval-jit-globals` would not be available if the VMVX HAL driver was not included in the build
2. If the compiler is enabled, enable the VMVX HAL driver
3. Always enable the VMVX HAL driver (change it from an option that can be turned off to a variable that is always on?)

Ben, you vote for option 3?

**Comment by benvanik** [comment]
2 or 3, maybe 2 - the intent of the IREE_HAL_DRIVER flags are to control what gets pulled into the default runtime builds via `iree/hal/drivers/init.h`. The fact that it _also_ entirely removes the build rules for registration is just for people who build :all so that it wouldn't build cuda on bare metal and such. But if in a cmake configuration you're building the compiler you've definitely got support for what VMVX needs and it has zero additional deps so having the rule around is harmless.

I still don't like any of this (vmvx is just a loader for the local CPU backend) but 2 feels like the easiest workaround - I'd probably just change the vmvx/registration/ cmakelist to be IREE_HAL_DRIVER_VMVX || IREE_BUILD_COMPILER.

**Comment by stellaraccident** [comment]
We always need a reference implementation that the compiler can use: otherwise, in the limit, there is no clear backend that is always suitable, although host codegen can be considered.

I think Ben and I are suggesting a different option: always leave the build rules for it but don't include them in the runtime. The const-eval stuff instantiates it's driver explicitly with an explicit dep. Those options primarily control what is built in to the tools/apis. Different things.

**Comment by stellaraccident** [comment]
I don't think it's an issue in this case, but we can leave the build rules and exclude from all.

**Comment by benvanik** [comment]
oo I like that - forgot about EXCLUDE_FROM_ALL - the fewer conditional rules the better!

**Comment by ScottTodd** [comment]
Here's my interpretation of that fourth option:

Make these always available (or gated on `IREE_BUILD_COMPILER`), maybe add some `EXCLUDE_FROM_ALL`?
https://github.com/google/iree/blob/0916baf04b08f5125ee6b9de65d0e9a11365a9b8/iree/hal/vmvx/registration/CMakeLists.txt#L13-L21

Then keep these checks?
https://github.com/google/iree/blob/0916baf04b08f5125ee6b9de65d0e9a11365a9b8/iree/hal/drivers/CMakeLists.txt#L19-L24

Anything explicitly depending on the registration (and not using `iree_hal_register_all_available_drivers`) can continue to do so.

**Comment by benvanik** [comment]
yeah - I think having them always there with EXCLUDE_FROM_ALL is good - there's no real reason to build them with :all as they'll get pulled in by the drivers/init if enabled and built there

**Comment by marbre** [comment]
I noticed this *issue* while documenting how to build the compiler for our bare-metal use-case: https://github.com/iml130/iree-bare-metal-arm#option-a-build-iree. I actually think always building the `VMVX` HAL driver is fine, even though the `VMVX_SYNC` driver would be sufficient for our use-case. Anyway, I clearly see that there should be a reference pass, but I dislike the error a users currently sees (it is unclear that why it has to be enabled). So gating this on `IREE_BUILD_COMPILER` or adding `EXCLUDE_FROM_ALL` sounds good (when opening the issue I just wasn't sure what would be a desired fix).

**Comment by benvanik** [comment]
makes sense! I wholeheartedly agree that the crossing of the streams of compiler/runtime with the flag is confusing to users so if we can make that cut I think we'll be in a better place. Thanks for raising this issue :)
