### ISSUE TITLE
LinalgTransforms triggers MLIRContext asserts in multithreaded environment

### ISSUE THREAD

**Issue by antiagainst** [google/iree#8947]
LLVM version bump https://github.com/google/iree/pull/8942 brings in River's changes https://reviews.llvm.org/D112021. Now there are asserts guarding against certain mutating APIs on `MLIRContext` under multithreaded environments. LinalgTransform ops triggers this in the `PassMager::run` API calls in transfrom op's `apply` method, e.g., 

https://github.com/google/iree/blob/6eac24d15ae44f6a400da6c97989861787851be0/llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/LinalgTransformOps.cpp#L702-L719

Affected tests are XFAIL'ed to push forward LLVM version bump.

**Comment by nicolasvasilache** [comment]
Note: Looking at River's change it seems that the issue is that some dialect declared as dependent in the pass is not already registered in the context. If it were, the condition 
```
  if (registry.isSubsetOf(impl->dialectsRegistry))
    return;
```
 would trigger before the assert.

I would tentatively think that the interp pass is missing registry information that the nested pass adds.
The easy fix may be to register dependent stuff for all nested passes.

If certains things are harder to register (e.g. external model or adding ops into dialects) then I think this is a deeper problem, potentially a problem with nested passes in general.

**Comment by shabalind** [comment]
I'm currently investigating a fix for this issue in the sandbox. We've hit it as well.

**Comment by shabalind** [comment]
A quick-fix for this issue is available here: https://github.com/google/iree-llvm-sandbox/pull/455

**Comment by ftynse** [comment]
> I would tentatively think that the interp pass is missing registry information that the nested pass adds.
The easy fix may be to register dependent stuff for all nested passes.

The check bails in presence of dialect extensions, without attempting to compare them. We have extensions from external models and the transform dialect...

**Comment by antiagainst** [comment]
Fixed by https://github.com/google/iree/pull/8963.
