### ISSUE TITLE
[Vulkan] albert_test.py failing with nan values

### ISSUE THREAD

**Issue by mariecwhite** [google/iree#9044]
Getting nan output values when running iree-samples/tflitehub/albert_test.py with driver vulkan.

To reproduce:
```
git clone https://github.com/<github_handle>/iree-samples
cd iree-samples

./setup_venv.sh
source iree-samples.venv/bin/activate

python tflitehub/albert_test.py --config=vulkan
```

**Comment by powderluv** [comment]
Seems like the NaN we see on Linux A100 
https://github.com/google/iree/issues/9447

**Comment by antiagainst** [comment]
It turns out that this is due incorrect handling of corner cases in `math.powf` to `spv.GLSL.Pow` conversion. Per `spv.GLSL.Pow` [spec](https://www.khronos.org/registry/SPIR-V/specs/1.0/GLSL.std.450.html):

> Result is x raised to the y power; xy. Result is undefined if x < 0. Result is undefined if x = 0 and y ≤ 0.

The first NaN-producing dispatches contains negative `x` values. For those negative `x` values, `spv.GLSL.Pow` returns `NaN` for them. For positive `x` values the results are correct.

**Comment by antiagainst** [comment]
Uploaded https://reviews.llvm.org/D127816 in the upstream to handle the negative values properly. https://github.com/google/iree/pull/9507 pulls it into IREE.

**Comment by powderluv** [comment]
nicely done
