### ISSUE TITLE
Quantized tflite model lowering 

### ISSUE THREAD

**Issue by ArunaKote** [google/iree#9112]
am trying  to understand how quantization in tf is handled in mlir.Can we convert quantized tflite model to tensorflow saved_model format? and also just wanted to is there any other path to lower tflite other than dialect? 

Thanks

**Comment by stellaraccident** [comment]
No, that is not possible and there is no other path available (you may be able to cobble something together for limited cases but it is not general or supported). The issue is with upstream Tensorflow: it lacks even the op coverage to represent a TFLite model, much less converters to do that. This has been a top all of mine for years with no progress, and we stopped expecting this to change. We invest new effort in Jax and PyTorch because such things are better aligned there.

**Comment by mariecwhite** [comment]
Hi Aruna,

If you're looking to understand how MLIR handles Tensorflow quantized models, I'm afraid converting a quantized TFLite model to a Tensorflow saved_model won't help since it's moving in the opposite direction. The information needed to convert from TF to TFLite would have been stripped away.

TF models with quantization info are converted into a quantized TFLite model using [tflite_convert](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/BUILD#L68), which is MLIR-based. I suggest stepping through this code to understand the quantization flow.

If you're looking for an example, there are some Tensorflow checkpoints available publicly with quantization info. The Spaghettinet models on [this page](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md#pixel-6-edge-tpu-models) contain pretrained TF models. You can run `tflite_convert` with `frozen_inference_graph.pb` as input. Note that the large version has a known issue but can be easily fixed with a [patch](https://github.com/tensorflow/models/issues/10320).

**Comment by dinkdeep** [comment]
Hi  @stellaraccident & @mariecwhite , Probably XLA too might be doing quantization, Do we have insight into that, Is there some reference sources in XLA where to precisely  look at . "We invest new effort in Jax and PyTorch because such things are better aligned there." May be you can kindly suggest the source files in JAX and  PyTorch so we can look around that too .
I believe there is a an mlir dialect  to convert pytorch and represent it similar to tf dialect and run native pytroch code through MLIR, So do we have some thing for quantitation on that path .

**Comment by stellaraccident** [comment]
Both tosa and xla have sufficient arithmetic coverage to express "quantized" math precisely (with some caveats). We sometimes call this "native quantization" but it is really just integer math. Conversions exist from TFLite to tosa for all quantized ops (we think), and I expect that those will emerge on the torch-mlir side similarly. I know of some projects to do similar things in XLA, but our primary use of quantization in Jax right now is just to train with quantization constraints and then run directly in integer.

In general, my opinion is that to the extent that quantization is a thing, it is mostly at the frontend level. When lowering to a compiler, it is typical to just do the integer math required explicitly.

I'm sorry - I wish I could be more specific. We are running various quantization workloads through all of the paths, but our TFLite support is the only one I would say is relatively complete and ready for use. The rest will take time. If interested in PyTorch specifically, be sure to ask on the torch-mlir project: that is where most of the work will be done. IREE should be able to compile the result just like it does from TFLite today.

For Jax, like I said, we are presently taking a more direct approach and skipping quantization altogether -- just training in integer directly. I know there are others working on other approaches, but I'm not up to speed on them.
